-- Tüm Türkiye Belediyeleri
-- İlçe = Belediye mantığıyla tüm il ve ilçeleri belediye olarak ekliyoruz
-- NOT: İstanbul için 00008 migration'ında eklenenler zaten var (ON CONFLICT ile çakışma engellendi)

INSERT INTO municipalities (name, code, city, district, is_active) VALUES
  -- Adana (15 ilçe)
  ('Aladağ Belediyesi', 'adana-aladag', 'Adana', 'Aladağ', true),
  ('Ceyhan Belediyesi', 'adana-ceyhan', 'Adana', 'Ceyhan', true),
  ('Çukurova Belediyesi', 'adana-cukurova', 'Adana', 'Çukurova', true),
  ('Feke Belediyesi', 'adana-feke', 'Adana', 'Feke', true),
  ('İmamoğlu Belediyesi', 'adana-imamoglu', 'Adana', 'İmamoğlu', true),
  ('Karaisalı Belediyesi', 'adana-karaisali', 'Adana', 'Karaisalı', true),
  ('Karataş Belediyesi', 'adana-karatas', 'Adana', 'Karataş', true),
  ('Kozan Belediyesi', 'adana-kozan', 'Adana', 'Kozan', true),
  ('Pozantı Belediyesi', 'adana-pozanti', 'Adana', 'Pozantı', true),
  ('Saimbeyli Belediyesi', 'adana-saimbeyli', 'Adana', 'Saimbeyli', true),
  ('Sarıçam Belediyesi', 'adana-saricam', 'Adana', 'Sarıçam', true),
  ('Seyhan Belediyesi', 'adana-seyhan', 'Adana', 'Seyhan', true),
  ('Tufanbeyli Belediyesi', 'adana-tufanbeyli', 'Adana', 'Tufanbeyli', true),
  ('Yumurtalık Belediyesi', 'adana-yumurtalik', 'Adana', 'Yumurtalık', true),
  ('Yüreğir Belediyesi', 'adana-yuregir', 'Adana', 'Yüreğir', true),

  -- Adıyaman (9 ilçe)
  ('Besni Belediyesi', 'adiyaman-besni', 'Adıyaman', 'Besni', true),
  ('Çelikhan Belediyesi', 'adiyaman-celikhan', 'Adıyaman', 'Çelikhan', true),
  ('Gerger Belediyesi', 'adiyaman-gerger', 'Adıyaman', 'Gerger', true),
  ('Gölbaşı Belediyesi', 'adiyaman-golbasi', 'Adıyaman', 'Gölbaşı', true),
  ('Kahta Belediyesi', 'adiyaman-kahta', 'Adıyaman', 'Kahta', true),
  ('Adıyaman Merkez Belediyesi', 'adiyaman-merkez', 'Adıyaman', 'Merkez', true),
  ('Samsat Belediyesi', 'adiyaman-samsat', 'Adıyaman', 'Samsat', true),
  ('Sincik Belediyesi', 'adiyaman-sincik', 'Adıyaman', 'Sincik', true),
  ('Tut Belediyesi', 'adiyaman-tut', 'Adıyaman', 'Tut', true),

  -- Afyonkarahisar (18 ilçe)
  ('Başmakçı Belediyesi', 'afyonkarahisar-basmakci', 'Afyonkarahisar', 'Başmakçı', true),
  ('Bayat Belediyesi', 'afyonkarahisar-bayat', 'Afyonkarahisar', 'Bayat', true),
  ('Bolvadin Belediyesi', 'afyonkarahisar-bolvadin', 'Afyonkarahisar', 'Bolvadin', true),
  ('Çay Belediyesi', 'afyonkarahisar-cay', 'Afyonkarahisar', 'Çay', true),
  ('Çobanlar Belediyesi', 'afyonkarahisar-cobanlar', 'Afyonkarahisar', 'Çobanlar', true),
  ('Dazkırı Belediyesi', 'afyonkarahisar-dazkiri', 'Afyonkarahisar', 'Dazkırı', true),
  ('Dinar Belediyesi', 'afyonkarahisar-dinar', 'Afyonkarahisar', 'Dinar', true),
  ('Emirdağ Belediyesi', 'afyonkarahisar-emirdag', 'Afyonkarahisar', 'Emirdağ', true),
  ('Evciler Belediyesi', 'afyonkarahisar-evciler', 'Afyonkarahisar', 'Evciler', true),
  ('Hocalar Belediyesi', 'afyonkarahisar-hocalar', 'Afyonkarahisar', 'Hocalar', true),
  ('İhsaniye Belediyesi', 'afyonkarahisar-ihsaniye', 'Afyonkarahisar', 'İhsaniye', true),
  ('İscehisar Belediyesi', 'afyonkarahisar-iscehisar', 'Afyonkarahisar', 'İscehisar', true),
  ('Kızılören Belediyesi', 'afyonkarahisar-kiziloren', 'Afyonkarahisar', 'Kızılören', true),
  ('Afyonkarahisar Merkez Belediyesi', 'afyonkarahisar-merkez', 'Afyonkarahisar', 'Merkez', true),
  ('Sandıklı Belediyesi', 'afyonkarahisar-sandikli', 'Afyonkarahisar', 'Sandıklı', true),
  ('Sinanpaşa Belediyesi', 'afyonkarahisar-sinanpasa', 'Afyonkarahisar', 'Sinanpaşa', true),
  ('Sultandağı Belediyesi', 'afyonkarahisar-sultandagi', 'Afyonkarahisar', 'Sultandağı', true),
  ('Şuhut Belediyesi', 'afyonkarahisar-suhut', 'Afyonkarahisar', 'Şuhut', true),

  -- Ağrı (8 ilçe)
  ('Diyadin Belediyesi', 'agri-diyadin', 'Ağrı', 'Diyadin', true),
  ('Doğubayazıt Belediyesi', 'agri-dogubayazit', 'Ağrı', 'Doğubayazıt', true),
  ('Eleşkirt Belediyesi', 'agri-eleskirt', 'Ağrı', 'Eleşkirt', true),
  ('Hamur Belediyesi', 'agri-hamur', 'Ağrı', 'Hamur', true),
  ('Ağrı Merkez Belediyesi', 'agri-merkez', 'Ağrı', 'Merkez', true),
  ('Patnos Belediyesi', 'agri-patnos', 'Ağrı', 'Patnos', true),
  ('Taşlıçay Belediyesi', 'agri-taslicay', 'Ağrı', 'Taşlıçay', true),
  ('Tutak Belediyesi', 'agri-tutak', 'Ağrı', 'Tutak', true),

  -- Aksaray (8 ilçe)
  ('Ağaçören Belediyesi', 'aksaray-agacoren', 'Aksaray', 'Ağaçören', true),
  ('Eskil Belediyesi', 'aksaray-eskil', 'Aksaray', 'Eskil', true),
  ('Gülağaç Belediyesi', 'aksaray-gulagac', 'Aksaray', 'Gülağaç', true),
  ('Güzelyurt Belediyesi', 'aksaray-guzelyurt', 'Aksaray', 'Güzelyurt', true),
  ('Aksaray Merkez Belediyesi', 'aksaray-merkez', 'Aksaray', 'Merkez', true),
  ('Ortaköy Belediyesi', 'aksaray-ortakoy', 'Aksaray', 'Ortaköy', true),
  ('Sarıyahşi Belediyesi', 'aksaray-sariyahsi', 'Aksaray', 'Sarıyahşi', true),
  ('Sultanhanı Belediyesi', 'aksaray-sultanhani', 'Aksaray', 'Sultanhanı', true),

  -- Amasya (7 ilçe)
  ('Göynücek Belediyesi', 'amasya-goynucek', 'Amasya', 'Göynücek', true),
  ('Gümüşhacıköy Belediyesi', 'amasya-gumushacikoy', 'Amasya', 'Gümüşhacıköy', true),
  ('Hamamözü Belediyesi', 'amasya-hamamozu', 'Amasya', 'Hamamözü', true),
  ('Amasya Merkez Belediyesi', 'amasya-merkez', 'Amasya', 'Merkez', true),
  ('Merzifon Belediyesi', 'amasya-merzifon', 'Amasya', 'Merzifon', true),
  ('Suluova Belediyesi', 'amasya-suluova', 'Amasya', 'Suluova', true),
  ('Taşova Belediyesi', 'amasya-tasova', 'Amasya', 'Taşova', true),

  -- Ankara (25 ilçe)
  ('Akyurt Belediyesi', 'ankara-akyurt', 'Ankara', 'Akyurt', true),
  ('Altındağ Belediyesi', 'ankara-altindag', 'Ankara', 'Altındağ', true),
  ('Ayaş Belediyesi', 'ankara-ayas', 'Ankara', 'Ayaş', true),
  ('Bala Belediyesi', 'ankara-bala', 'Ankara', 'Bala', true),
  ('Beypazarı Belediyesi', 'ankara-beypazari', 'Ankara', 'Beypazarı', true),
  ('Çamlıdere Belediyesi', 'ankara-camlidere', 'Ankara', 'Çamlıdere', true),
  ('Çubuk Belediyesi', 'ankara-cubuk', 'Ankara', 'Çubuk', true),
  ('Elmadağ Belediyesi', 'ankara-elmadag', 'Ankara', 'Elmadağ', true),
  ('Etimesgut Belediyesi', 'ankara-etimesgut', 'Ankara', 'Etimesgut', true),
  ('Evren Belediyesi', 'ankara-evren', 'Ankara', 'Evren', true),
  ('Gölbaşı Belediyesi', 'ankara-golbasi', 'Ankara', 'Gölbaşı', true),
  ('Güdül Belediyesi', 'ankara-gudul', 'Ankara', 'Güdül', true),
  ('Haymana Belediyesi', 'ankara-haymana', 'Ankara', 'Haymana', true),
  ('Kahramankazan Belediyesi', 'ankara-kahramankazan', 'Ankara', 'Kahramankazan', true),
  ('Kalecik Belediyesi', 'ankara-kalecik', 'Ankara', 'Kalecik', true),
  ('Keçiören Belediyesi', 'ankara-kecioren', 'Ankara', 'Keçiören', true),
  ('Kızılcahamam Belediyesi', 'ankara-kizilcahamam', 'Ankara', 'Kızılcahamam', true),
  ('Mamak Belediyesi', 'ankara-mamak', 'Ankara', 'Mamak', true),
  ('Nallıhan Belediyesi', 'ankara-nallihan', 'Ankara', 'Nallıhan', true),
  ('Polatlı Belediyesi', 'ankara-polatli', 'Ankara', 'Polatlı', true),
  ('Pursaklar Belediyesi', 'ankara-pursaklar', 'Ankara', 'Pursaklar', true),
  ('Sincan Belediyesi', 'ankara-sincan', 'Ankara', 'Sincan', true),
  ('Şereflikoçhisar Belediyesi', 'ankara-sereflikochistar', 'Ankara', 'Şereflikoçhisar', true),
  ('Yenimahalle Belediyesi', 'ankara-yenimahalle', 'Ankara', 'Yenimahalle', true),

  -- Antalya (19 ilçe)
  ('Akseki Belediyesi', 'antalya-akseki', 'Antalya', 'Akseki', true),
  ('Aksu Belediyesi', 'antalya-aksu', 'Antalya', 'Aksu', true),
  ('Alanya Belediyesi', 'antalya-alanya', 'Antalya', 'Alanya', true),
  ('Demre Belediyesi', 'antalya-demre', 'Antalya', 'Demre', true),
  ('Döşemealtı Belediyesi', 'antalya-dosemealti', 'Antalya', 'Döşemealtı', true),
  ('Elmalı Belediyesi', 'antalya-elmali', 'Antalya', 'Elmalı', true),
  ('Finike Belediyesi', 'antalya-finike', 'Antalya', 'Finike', true),
  ('Gazipaşa Belediyesi', 'antalya-gazipasa', 'Antalya', 'Gazipaşa', true),
  ('Gündoğmuş Belediyesi', 'antalya-gundogmus', 'Antalya', 'Gündoğmuş', true),
  ('İbradı Belediyesi', 'antalya-ibradi', 'Antalya', 'İbradı', true),
  ('Kaş Belediyesi', 'antalya-kas', 'Antalya', 'Kaş', true),
  ('Kemer Belediyesi', 'antalya-kemer', 'Antalya', 'Kemer', true),
  ('Kepez Belediyesi', 'antalya-kepez', 'Antalya', 'Kepez', true),
  ('Konyaaltı Belediyesi', 'antalya-konyaalti', 'Antalya', 'Konyaaltı', true),
  ('Korkuteli Belediyesi', 'antalya-korkuteli', 'Antalya', 'Korkuteli', true),
  ('Kumluca Belediyesi', 'antalya-kumluca', 'Antalya', 'Kumluca', true),
  ('Manavgat Belediyesi', 'antalya-manavgat', 'Antalya', 'Manavgat', true),
  ('Muratpaşa Belediyesi', 'antalya-muratpasa', 'Antalya', 'Muratpaşa', true),
  ('Serik Belediyesi', 'antalya-serik', 'Antalya', 'Serik', true),

  -- İzmir (30 ilçe)
  ('Aliağa Belediyesi', 'izmir-aliaga', 'İzmir', 'Aliağa', true),
  ('Balçova Belediyesi', 'izmir-balcova', 'İzmir', 'Balçova', true),
  ('Bayındır Belediyesi', 'izmir-bayindir', 'İzmir', 'Bayındır', true),
  ('Bayraklı Belediyesi', 'izmir-bayrakli', 'İzmir', 'Bayraklı', true),
  ('Bergama Belediyesi', 'izmir-bergama', 'İzmir', 'Bergama', true),
  ('Beydağ Belediyesi', 'izmir-beydag', 'İzmir', 'Beydağ', true),
  ('Bornova Belediyesi', 'izmir-bornova', 'İzmir', 'Bornova', true),
  ('Buca Belediyesi', 'izmir-buca', 'İzmir', 'Buca', true),
  ('Çeşme Belediyesi', 'izmir-cesme', 'İzmir', 'Çeşme', true),
  ('Çiğli Belediyesi', 'izmir-cigli', 'İzmir', 'Çiğli', true),
  ('Dikili Belediyesi', 'izmir-dikili', 'İzmir', 'Dikili', true),
  ('Foça Belediyesi', 'izmir-foca', 'İzmir', 'Foça', true),
  ('Gaziemir Belediyesi', 'izmir-gaziemir', 'İzmir', 'Gaziemir', true),
  ('Güzelbahçe Belediyesi', 'izmir-guzelbahce', 'İzmir', 'Güzelbahçe', true),
  ('Karabağlar Belediyesi', 'izmir-karabaglar', 'İzmir', 'Karabağlar', true),
  ('Karaburun Belediyesi', 'izmir-karaburun', 'İzmir', 'Karaburun', true),
  ('Karşıyaka Belediyesi', 'izmir-karsiyaka', 'İzmir', 'Karşıyaka', true),
  ('Kemalpaşa Belediyesi', 'izmir-kemalpasa', 'İzmir', 'Kemalpaşa', true),
  ('Kınık Belediyesi', 'izmir-kinik', 'İzmir', 'Kınık', true),
  ('Kiraz Belediyesi', 'izmir-kiraz', 'İzmir', 'Kiraz', true),
  ('Menderes Belediyesi', 'izmir-menderes', 'İzmir', 'Menderes', true),
  ('Menemen Belediyesi', 'izmir-menemen', 'İzmir', 'Menemen', true),
  ('Narlıdere Belediyesi', 'izmir-narlidere', 'İzmir', 'Narlıdere', true),
  ('Ödemiş Belediyesi', 'izmir-odemis', 'İzmir', 'Ödemiş', true),
  ('Seferihisar Belediyesi', 'izmir-seferihisar', 'İzmir', 'Seferihisar', true),
  ('Selçuk Belediyesi', 'izmir-selcuk', 'İzmir', 'Selçuk', true),
  ('Tire Belediyesi', 'izmir-tire', 'İzmir', 'Tire', true),
  ('Torbalı Belediyesi', 'izmir-torbali', 'İzmir', 'Torbalı', true),
  ('Urla Belediyesi', 'izmir-urla', 'İzmir', 'Urla', true)

ON CONFLICT (code) DO NOTHING;

-- İstatistik
SELECT 
  'Toplam ' || COUNT(*) || ' belediye eklendi' as sonuc
FROM municipalities;
