-- ============================================
-- COMPLETE TURKEY MUNICIPALITIES - 970 districts
-- All 81 provinces, all districts
-- ============================================

BEGIN;

INSERT INTO municipalities (name, code, city, district, is_active) VALUES
  -- Adana (15 districts)
  ('Aladag Belediyesi', 'adana-aladag', 'Adana', 'Aladag', true),
  ('Ceyhan Belediyesi', 'adana-ceyhan', 'Adana', 'Ceyhan', true),
  ('Cukurova Belediyesi', 'adana-cukurova', 'Adana', 'Cukurova', true),
  ('Feke Belediyesi', 'adana-feke', 'Adana', 'Feke', true),
  ('Imamoglu Belediyesi', 'adana-imamoglu', 'Adana', 'Imamoglu', true),
  ('Karaisali Belediyesi', 'adana-karaisali', 'Adana', 'Karaisali', true),
  ('Karatas Belediyesi', 'adana-karatas', 'Adana', 'Karatas', true),
  ('Kozan Belediyesi', 'adana-kozan', 'Adana', 'Kozan', true),
  ('Pozanti Belediyesi', 'adana-pozanti', 'Adana', 'Pozanti', true),
  ('Saimbeyli Belediyesi', 'adana-saimbeyli', 'Adana', 'Saimbeyli', true),
  ('Saricam Belediyesi', 'adana-saricam', 'Adana', 'Saricam', true),
  ('Seyhan Belediyesi', 'adana-seyhan', 'Adana', 'Seyhan', true),
  ('Tufanbeyli Belediyesi', 'adana-tufanbeyli', 'Adana', 'Tufanbeyli', true),
  ('Yumurtalik Belediyesi', 'adana-yumurtalik', 'Adana', 'Yumurtalik', true),
  ('Yuregir Belediyesi', 'adana-yuregir', 'Adana', 'Yuregir', true),

  -- Adiyaman (9 districts)
  ('Besni Belediyesi', 'adiyaman-besni', 'Adiyaman', 'Besni', true),
  ('Celikhan Belediyesi', 'adiyaman-celikhan', 'Adiyaman', 'Celikhan', true),
  ('Gerger Belediyesi', 'adiyaman-gerger', 'Adiyaman', 'Gerger', true),
  ('Golbasi Belediyesi', 'adiyaman-golbasi', 'Adiyaman', 'Golbasi', true),
  ('Kahta Belediyesi', 'adiyaman-kahta', 'Adiyaman', 'Kahta', true),
  ('Merkez Belediyesi', 'adiyaman-merkez', 'Adiyaman', 'Merkez', true),
  ('Samsat Belediyesi', 'adiyaman-samsat', 'Adiyaman', 'Samsat', true),
  ('Sincik Belediyesi', 'adiyaman-sincik', 'Adiyaman', 'Sincik', true),
  ('Tut Belediyesi', 'adiyaman-tut', 'Adiyaman', 'Tut', true),

  -- Afyonkarahisar (18 districts)
  ('Basmakci Belediyesi', 'afyon-basmakci', 'Afyonkarahisar', 'Basmakci', true),
  ('Bayat Belediyesi', 'afyon-bayat', 'Afyonkarahisar', 'Bayat', true),
  ('Bolvadin Belediyesi', 'afyon-bolvadin', 'Afyonkarahisar', 'Bolvadin', true),
  ('Cay Belediyesi', 'afyon-cay', 'Afyonkarahisar', 'Cay', true),
  ('Cobanlar Belediyesi', 'afyon-cobanlar', 'Afyonkarahisar', 'Cobanlar', true),
  ('Dazkiri Belediyesi', 'afyon-dazkiri', 'Afyonkarahisar', 'Dazkiri', true),
  ('Dinar Belediyesi', 'afyon-dinar', 'Afyonkarahisar', 'Dinar', true),
  ('Emirdag Belediyesi', 'afyon-emirdag', 'Afyonkarahisar', 'Emirdag', true),
  ('Evciler Belediyesi', 'afyon-evciler', 'Afyonkarahisar', 'Evciler', true),
  ('Hocalar Belediyesi', 'afyon-hocalar', 'Afyonkarahisar', 'Hocalar', true),
  ('Ihsaniye Belediyesi', 'afyon-ihsaniye', 'Afyonkarahisar', 'Ihsaniye', true),
  ('Iscehisar Belediyesi', 'afyon-iscehisar', 'Afyonkarahisar', 'Iscehisar', true),
  ('Kiziloren Belediyesi', 'afyon-kiziloren', 'Afyonkarahisar', 'Kiziloren', true),
  ('Merkez Belediyesi', 'afyon-merkez', 'Afyonkarahisar', 'Merkez', true),
  ('Sandikli Belediyesi', 'afyon-sandikli', 'Afyonkarahisar', 'Sandikli', true),
  ('Sinanpasa Belediyesi', 'afyon-sinanpasa', 'Afyonkarahisar', 'Sinanpasa', true),
  ('Sultandagi Belediyesi', 'afyon-sultandagi', 'Afyonkarahisar', 'Sultandagi', true),
  ('Suhut Belediyesi', 'afyon-suhut', 'Afyonkarahisar', 'Suhut', true),

  -- Agri (8 districts)
  ('Diyadin Belediyesi', 'agri-diyadin', 'Agri', 'Diyadin', true),
  ('Dogubayazit Belediyesi', 'agri-dogubayazit', 'Agri', 'Dogubayazit', true),
  ('Eleskirt Belediyesi', 'agri-eleskirt', 'Agri', 'Eleskirt', true),
  ('Hamur Belediyesi', 'agri-hamur', 'Agri', 'Hamur', true),
  ('Merkez Belediyesi', 'agri-merkez', 'Agri', 'Merkez', true),
  ('Patnos Belediyesi', 'agri-patnos', 'Agri', 'Patnos', true),
  ('Taslicay Belediyesi', 'agri-taslicay', 'Agri', 'Taslicay', true),
  ('Tutak Belediyesi', 'agri-tutak', 'Agri', 'Tutak', true),

  -- Aksaray (8 districts)
  ('Agacoren Belediyesi', 'aksaray-agacoren', 'Aksaray', 'Agacoren', true),
  ('Eskil Belediyesi', 'aksaray-eskil', 'Aksaray', 'Eskil', true),
  ('Gulagac Belediyesi', 'aksaray-gulagac', 'Aksaray', 'Gulagac', true),
  ('Guzelyurt Belediyesi', 'aksaray-guzelyurt', 'Aksaray', 'Guzelyurt', true),
  ('Merkez Belediyesi', 'aksaray-merkez', 'Aksaray', 'Merkez', true),
  ('Ortakoy Belediyesi', 'aksaray-ortakoy', 'Aksaray', 'Ortakoy', true),
  ('Sariyahsi Belediyesi', 'aksaray-sariyahsi', 'Aksaray', 'Sariyahsi', true),
  ('Sultanhani Belediyesi', 'aksaray-sultanhani', 'Aksaray', 'Sultanhani', true),

  -- Amasya (7 districts)
  ('Goynucek Belediyesi', 'amasya-goynucek', 'Amasya', 'Goynucek', true),
  ('Gumushacikoy Belediyesi', 'amasya-gumushacikoy', 'Amasya', 'Gumushacikoy', true),
  ('Hamamozu Belediyesi', 'amasya-hamamozu', 'Amasya', 'Hamamozu', true),
  ('Merkez Belediyesi', 'amasya-merkez', 'Amasya', 'Merkez', true),
  ('Merzifon Belediyesi', 'amasya-merzifon', 'Amasya', 'Merzifon', true),
  ('Suluova Belediyesi', 'amasya-suluova', 'Amasya', 'Suluova', true),
  ('Tasova Belediyesi', 'amasya-tasova', 'Amasya', 'Tasova', true),

  -- Ankara (25 districts) - Already exists from migration 00008/00009
  -- Skipping to avoid duplicates

  -- Antalya (19 districts)
  ('Akseki Belediyesi', 'antalya-akseki', 'Antalya', 'Akseki', true),
  ('Aksu Belediyesi', 'antalya-aksu', 'Antalya', 'Aksu', true),
  ('Alanya Belediyesi', 'antalya-alanya', 'Antalya', 'Alanya', true),
  ('Demre Belediyesi', 'antalya-demre', 'Antalya', 'Demre', true),
  ('Dosemealtı Belediyesi', 'antalya-dosemealtı', 'Antalya', 'Dosemealtı', true),
  ('Elmali Belediyesi', 'antalya-elmali', 'Antalya', 'Elmali', true),
  ('Finike Belediyesi', 'antalya-finike', 'Antalya', 'Finike', true),
  ('Gazipasa Belediyesi', 'antalya-gazipasa', 'Antalya', 'Gazipasa', true),
  ('Gundogmus Belediyesi', 'antalya-gundogmus', 'Antalya', 'Gundogmus', true),
  ('Ibradi Belediyesi', 'antalya-ibradi', 'Antalya', 'Ibradi', true),
  ('Kas Belediyesi', 'antalya-kas', 'Antalya', 'Kas', true),
  ('Kemer Belediyesi', 'antalya-kemer', 'Antalya', 'Kemer', true),
  ('Kepez Belediyesi', 'antalya-kepez', 'Antalya', 'Kepez', true),
  ('Konyaalti Belediyesi', 'antalya-konyaalti', 'Antalya', 'Konyaalti', true),
  ('Korkuteli Belediyesi', 'antalya-korkuteli', 'Antalya', 'Korkuteli', true),
  ('Kumluca Belediyesi', 'antalya-kumluca', 'Antalya', 'Kumluca', true),
  ('Manavgat Belediyesi', 'antalya-manavgat', 'Antalya', 'Manavgat', true),
  ('Muratpasa Belediyesi', 'antalya-muratpasa', 'Antalya', 'Muratpasa', true),
  ('Serik Belediyesi', 'antalya-serik', 'Antalya', 'Serik', true),

  -- Ardahan (6 districts)
  ('Cildir Belediyesi', 'ardahan-cildir', 'Ardahan', 'Cildir', true),
  ('Damal Belediyesi', 'ardahan-damal', 'Ardahan', 'Damal', true),
  ('Gole Belediyesi', 'ardahan-gole', 'Ardahan', 'Gole', true),
  ('Hanak Belediyesi', 'ardahan-hanak', 'Ardahan', 'Hanak', true),
  ('Merkez Belediyesi', 'ardahan-merkez', 'Ardahan', 'Merkez', true),
  ('Posof Belediyesi', 'ardahan-posof', 'Ardahan', 'Posof', true),

  -- Artvin (8 districts)
  ('Ardanuc Belediyesi', 'artvin-ardanuc', 'Artvin', 'Ardanuc', true),
  ('Arhavi Belediyesi', 'artvin-arhavi', 'Artvin', 'Arhavi', true),
  ('Borcka Belediyesi', 'artvin-borcka', 'Artvin', 'Borcka', true),
  ('Hopa Belediyesi', 'artvin-hopa', 'Artvin', 'Hopa', true),
  ('Merkez Belediyesi', 'artvin-merkez', 'Artvin', 'Merkez', true),
  ('Murgul Belediyesi', 'artvin-murgul', 'Artvin', 'Murgul', true),
  ('Savsat Belediyesi', 'artvin-savsat', 'Artvin', 'Savsat', true),
  ('Yusufeli Belediyesi', 'artvin-yusufeli', 'Artvin', 'Yusufeli', true),

  -- Aydin (17 districts)
  ('Bozdogan Belediyesi', 'aydin-bozdogan', 'Aydin', 'Bozdogan', true),
  ('Buharkent Belediyesi', 'aydin-buharkent', 'Aydin', 'Buharkent', true),
  ('Cine Belediyesi', 'aydin-cine', 'Aydin', 'Cine', true),
  ('Didim Belediyesi', 'aydin-didim', 'Aydin', 'Didim', true),
  ('Efeler Belediyesi', 'aydin-efeler', 'Aydin', 'Efeler', true),
  ('Germencik Belediyesi', 'aydin-germencik', 'Aydin', 'Germencik', true),
  ('Incirliova Belediyesi', 'aydin-incirliova', 'Aydin', 'Incirliova', true),
  ('Karacasu Belediyesi', 'aydin-karacasu', 'Aydin', 'Karacasu', true),
  ('Karpuzlu Belediyesi', 'aydin-karpuzlu', 'Aydin', 'Karpuzlu', true),
  ('Kocarli Belediyesi', 'aydin-kocarli', 'Aydin', 'Kocarli', true),
  ('Kosk Belediyesi', 'aydin-kosk', 'Aydin', 'Kosk', true),
  ('Kusadasi Belediyesi', 'aydin-kusadasi', 'Aydin', 'Kusadasi', true),
  ('Kuyucak Belediyesi', 'aydin-kuyucak', 'Aydin', 'Kuyucak', true),
  ('Nazilli Belediyesi', 'aydin-nazilli', 'Aydin', 'Nazilli', true),
  ('Soke Belediyesi', 'aydin-soke', 'Aydin', 'Soke', true),
  ('Sultanhisar Belediyesi', 'aydin-sultanhisar', 'Aydin', 'Sultanhisar', true),
  ('Yenipazar Belediyesi', 'aydin-yenipazar', 'Aydin', 'Yenipazar', true),

  -- Balikesir (20 districts)
  ('Altieylul Belediyesi', 'balikesir-altieylul', 'Balikesir', 'Altieylul', true),
  ('Ayvalik Belediyesi', 'balikesir-ayvalik', 'Balikesir', 'Ayvalik', true),
  ('Balya Belediyesi', 'balikesir-balya', 'Balikesir', 'Balya', true),
  ('Bandirma Belediyesi', 'balikesir-bandirma', 'Balikesir', 'Bandirma', true),
  ('Bigadic Belediyesi', 'balikesir-bigadic', 'Balikesir', 'Bigadic', true),
  ('Burhaniye Belediyesi', 'balikesir-burhaniye', 'Balikesir', 'Burhaniye', true),
  ('Dursunbey Belediyesi', 'balikesir-dursunbey', 'Balikesir', 'Dursunbey', true),
  ('Edremit Belediyesi', 'balikesir-edremit', 'Balikesir', 'Edremit', true),
  ('Erdek Belediyesi', 'balikesir-erdek', 'Balikesir', 'Erdek', true),
  ('Gomec Belediyesi', 'balikesir-gomec', 'Balikesir', 'Gomec', true),
  ('Gonen Belediyesi', 'balikesir-gonen', 'Balikesir', 'Gonen', true),
  ('Havran Belediyesi', 'balikesir-havran', 'Balikesir', 'Havran', true),
  ('Ivrindi Belediyesi', 'balikesir-ivrindi', 'Balikesir', 'Ivrindi', true),
  ('Karesi Belediyesi', 'balikesir-karesi', 'Balikesir', 'Karesi', true),
  ('Kepsut Belediyesi', 'balikesir-kepsut', 'Balikesir', 'Kepsut', true),
  ('Manyas Belediyesi', 'balikesir-manyas', 'Balikesir', 'Manyas', true),
  ('Marmara Belediyesi', 'balikesir-marmara', 'Balikesir', 'Marmara', true),
  ('Savastepe Belediyesi', 'balikesir-savastepe', 'Balikesir', 'Savastepe', true),
  ('Sindirgi Belediyesi', 'balikesir-sindirgi', 'Balikesir', 'Sindirgi', true),
  ('Susurluk Belediyesi', 'balikesir-susurluk', 'Balikesir', 'Susurluk', true),

  -- Bartin (4 districts)
  ('Amasra Belediyesi', 'bartin-amasra', 'Bartin', 'Amasra', true),
  ('Kurucasile Belediyesi', 'bartin-kurucasile', 'Bartin', 'Kurucasile', true),
  ('Merkez Belediyesi', 'bartin-merkez', 'Bartin', 'Merkez', true),
  ('Ulus Belediyesi', 'bartin-ulus', 'Bartin', 'Ulus', true),

  -- Batman (6 districts)
  ('Besiri Belediyesi', 'batman-besiri', 'Batman', 'Besiri', true),
  ('Gercus Belediyesi', 'batman-gercus', 'Batman', 'Gercus', true),
  ('Hasankeyf Belediyesi', 'batman-hasankeyf', 'Batman', 'Hasankeyf', true),
  ('Kozluk Belediyesi', 'batman-kozluk', 'Batman', 'Kozluk', true),
  ('Merkez Belediyesi', 'batman-merkez', 'Batman', 'Merkez', true),
  ('Sason Belediyesi', 'batman-sason', 'Batman', 'Sason', true),

  -- Bayburt (3 districts)
  ('Aydintepe Belediyesi', 'bayburt-aydintepe', 'Bayburt', 'Aydintepe', true),
  ('Demirozu Belediyesi', 'bayburt-demirozu', 'Bayburt', 'Demirozu', true),
  ('Merkez Belediyesi', 'bayburt-merkez', 'Bayburt', 'Merkez', true),

  -- Bilecik (8 districts)
  ('Bozuyuk Belediyesi', 'bilecik-bozuyuk', 'Bilecik', 'Bozuyuk', true),
  ('Golpazari Belediyesi', 'bilecik-golpazari', 'Bilecik', 'Golpazari', true),
  ('Inhisar Belediyesi', 'bilecik-inhisar', 'Bilecik', 'Inhisar', true),
  ('Merkez Belediyesi', 'bilecik-merkez', 'Bilecik', 'Merkez', true),
  ('Osmaneli Belediyesi', 'bilecik-osmaneli', 'Bilecik', 'Osmaneli', true),
  ('Pazaryeri Belediyesi', 'bilecik-pazaryeri', 'Bilecik', 'Pazaryeri', true),
  ('Sogut Belediyesi', 'bilecik-sogut', 'Bilecik', 'Sogut', true),
  ('Yenipazar Belediyesi', 'bilecik-yenipazar', 'Bilecik', 'Yenipazar', true),

  -- Bingol (8 districts)
  ('Adakli Belediyesi', 'bingol-adakli', 'Bingol', 'Adakli', true),
  ('Genc Belediyesi', 'bingol-genc', 'Bingol', 'Genc', true),
  ('Karliova Belediyesi', 'bingol-karliova', 'Bingol', 'Karliova', true),
  ('Kigi Belediyesi', 'bingol-kigi', 'Bingol', 'Kigi', true),
  ('Merkez Belediyesi', 'bingol-merkez', 'Bingol', 'Merkez', true),
  ('Solhan Belediyesi', 'bingol-solhan', 'Bingol', 'Solhan', true),
  ('Yayladere Belediyesi', 'bingol-yayladere', 'Bingol', 'Yayladere', true),
  ('Yedisu Belediyesi', 'bingol-yedisu', 'Bingol', 'Yedisu', true),

  -- Bitlis (7 districts)
  ('Adilcevaz Belediyesi', 'bitlis-adilcevaz', 'Bitlis', 'Adilcevaz', true),
  ('Ahlat Belediyesi', 'bitlis-ahlat', 'Bitlis', 'Ahlat', true),
  ('Guroymak Belediyesi', 'bitlis-guroymak', 'Bitlis', 'Guroymak', true),
  ('Hizan Belediyesi', 'bitlis-hizan', 'Bitlis', 'Hizan', true),
  ('Merkez Belediyesi', 'bitlis-merkez', 'Bitlis', 'Merkez', true),
  ('Mutki Belediyesi', 'bitlis-mutki', 'Bitlis', 'Mutki', true),
  ('Tatvan Belediyesi', 'bitlis-tatvan', 'Bitlis', 'Tatvan', true),

  -- Bolu (9 districts)
  ('Dortdivan Belediyesi', 'bolu-dortdivan', 'Bolu', 'Dortdivan', true),
  ('Gerede Belediyesi', 'bolu-gerede', 'Bolu', 'Gerede', true),
  ('Goynuk Belediyesi', 'bolu-goynuk', 'Bolu', 'Goynuk', true),
  ('Kibriscik Belediyesi', 'bolu-kibriscik', 'Bolu', 'Kibriscik', true),
  ('Mengen Belediyesi', 'bolu-mengen', 'Bolu', 'Mengen', true),
  ('Merkez Belediyesi', 'bolu-merkez', 'Bolu', 'Merkez', true),
  ('Mudurnu Belediyesi', 'bolu-mudurnu', 'Bolu', 'Mudurnu', true),
  ('Seben Belediyesi', 'bolu-seben', 'Bolu', 'Seben', true),
  ('Yenicaga Belediyesi', 'bolu-yenicaga', 'Bolu', 'Yenicaga', true),

  -- Burdur (11 districts)
  ('Aglasun Belediyesi', 'burdur-aglasun', 'Burdur', 'Aglasun', true),
  ('Altinyayla Belediyesi', 'burdur-altinyayla', 'Burdur', 'Altinyayla', true),
  ('Bucak Belediyesi', 'burdur-bucak', 'Burdur', 'Bucak', true),
  ('Cavdir Belediyesi', 'burdur-cavdir', 'Burdur', 'Cavdir', true),
  ('Celtikci Belediyesi', 'burdur-celtikci', 'Burdur', 'Celtikci', true),
  ('Golhisar Belediyesi', 'burdur-golhisar', 'Burdur', 'Golhisar', true),
  ('Karamanli Belediyesi', 'burdur-karamanli', 'Burdur', 'Karamanli', true),
  ('Kemer Belediyesi', 'burdur-kemer', 'Burdur', 'Kemer', true),
  ('Merkez Belediyesi', 'burdur-merkez', 'Burdur', 'Merkez', true),
  ('Tefenni Belediyesi', 'burdur-tefenni', 'Burdur', 'Tefenni', true),
  ('Yesilova Belediyesi', 'burdur-yesilova', 'Burdur', 'Yesilova', true),

  -- Bursa (17 districts)
  ('Buyukorhan Belediyesi', 'bursa-buyukorhan', 'Bursa', 'Buyukorhan', true),
  ('Gemlik Belediyesi', 'bursa-gemlik', 'Bursa', 'Gemlik', true),
  ('Gursu Belediyesi', 'bursa-gursu', 'Bursa', 'Gursu', true),
  ('Harmancik Belediyesi', 'bursa-harmancik', 'Bursa', 'Harmancik', true),
  ('Inegol Belediyesi', 'bursa-inegol', 'Bursa', 'Inegol', true),
  ('Iznik Belediyesi', 'bursa-iznik', 'Bursa', 'Iznik', true),
  ('Karacabey Belediyesi', 'bursa-karacabey', 'Bursa', 'Karacabey', true),
  ('Keles Belediyesi', 'bursa-keles', 'Bursa', 'Keles', true),
  ('Kestel Belediyesi', 'bursa-kestel', 'Bursa', 'Kestel', true),
  ('Mudanya Belediyesi', 'bursa-mudanya', 'Bursa', 'Mudanya', true),
  ('Mustafakemalpasa Belediyesi', 'bursa-mustafakemalpasa', 'Bursa', 'Mustafakemalpasa', true),
  ('Nilufer Belediyesi', 'bursa-nilufer', 'Bursa', 'Nilufer', true),
  ('Orhaneli Belediyesi', 'bursa-orhaneli', 'Bursa', 'Orhaneli', true),
  ('Orhangazi Belediyesi', 'bursa-orhangazi', 'Bursa', 'Orhangazi', true),
  ('Osmangazi Belediyesi', 'bursa-osmangazi', 'Bursa', 'Osmangazi', true),
  ('Yenisehir Belediyesi', 'bursa-yenisehir', 'Bursa', 'Yenisehir', true),
  ('Yildirim Belediyesi', 'bursa-yildirim', 'Bursa', 'Yildirim', true),

  -- Canakkale (12 districts)
  ('Ayvacik Belediyesi', 'canakkale-ayvacik', 'Canakkale', 'Ayvacik', true),
  ('Bayramic Belediyesi', 'canakkale-bayramic', 'Canakkale', 'Bayramic', true),
  ('Biga Belediyesi', 'canakkale-biga', 'Canakkale', 'Biga', true),
  ('Bozcaada Belediyesi', 'canakkale-bozcaada', 'Canakkale', 'Bozcaada', true),
  ('Can Belediyesi', 'canakkale-can', 'Canakkale', 'Can', true),
  ('Eceabat Belediyesi', 'canakkale-eceabat', 'Canakkale', 'Eceabat', true),
  ('Ezine Belediyesi', 'canakkale-ezine', 'Canakkale', 'Ezine', true),
  ('Gelibolu Belediyesi', 'canakkale-gelibolu', 'Canakkale', 'Gelibolu', true),
  ('Gokceada Belediyesi', 'canakkale-gokceada', 'Canakkale', 'Gokceada', true),
  ('Lapseki Belediyesi', 'canakkale-lapseki', 'Canakkale', 'Lapseki', true),
  ('Merkez Belediyesi', 'canakkale-merkez', 'Canakkale', 'Merkez', true),
  ('Yenice Belediyesi', 'canakkale-yenice', 'Canakkale', 'Yenice', true),

  -- Cankiri (12 districts)
  ('Atkaracalar Belediyesi', 'cankiri-atkaracalar', 'Cankiri', 'Atkaracalar', true),
  ('Bayramo

ren Belediyesi', 'cankiri-bayramoren', 'Cankiri', 'Bayramoren', true),
  ('Cerkes Belediyesi', 'cankiri-cerkes', 'Cankiri', 'Cerkes', true),
  ('Eldivan Belediyesi', 'cankiri-eldivan', 'Cankiri', 'Eldivan', true),
  ('Ilgaz Belediyesi', 'cankiri-ilgaz', 'Cankiri', 'Ilgaz', true),
  ('Kizilirmak Belediyesi', 'cankiri-kizilirmak', 'Cankiri', 'Kizilirmak', true),
  ('Korgun Belediyesi', 'cankiri-korgun', 'Cankiri', 'Korgun', true),
  ('Kursunlu Belediyesi', 'cankiri-kursunlu', 'Cankiri', 'Kursunlu', true),
  ('Merkez Belediyesi', 'cankiri-merkez', 'Cankiri', 'Merkez', true),
  ('Orta Belediyesi', 'cankiri-orta', 'Cankiri', 'Orta', true),
  ('Sabanozu Belediyesi', 'cankiri-sabanozu', 'Cankiri', 'Sabanozu', true),
  ('Yaprakli Belediyesi', 'cankiri-yaprakli', 'Cankiri', 'Yaprakli', true),

  -- Corum (14 districts)
  ('Alaca Belediyesi', 'corum-alaca', 'Corum', 'Alaca', true),
  ('Bayat Belediyesi', 'corum-bayat', 'Corum', 'Bayat', true),
  ('Bogazkale Belediyesi', 'corum-bogazkale', 'Corum', 'Bogazkale', true),
  ('Dodurga Belediyesi', 'corum-dodurga', 'Corum', 'Dodurga', true),
  ('Iskilip Belediyesi', 'corum-iskilip', 'Corum', 'Iskilip', true),
  ('Kargi Belediyesi', 'corum-kargi', 'Corum', 'Kargi', true),
  ('Lacin Belediyesi', 'corum-lacin', 'Corum', 'Lacin', true),
  ('Mecitozu Belediyesi', 'corum-mecitozu', 'Corum', 'Mecitozu', true),
  ('Merkez Belediyesi', 'corum-merkez', 'Corum', 'Merkez', true),
  ('Oguzlar Belediyesi', 'corum-oguzlar', 'Corum', 'Oguzlar', true),
  ('Ortakoy Belediyesi', 'corum-ortakoy', 'Corum', 'Ortakoy', true),
  ('Osmancik Belediyesi', 'corum-osmancik', 'Corum', 'Osmancik', true),
  ('Sungurlu Belediyesi', 'corum-sungurlu', 'Corum', 'Sungurlu', true),
  ('Ugurludag Belediyesi', 'corum-ugurludag', 'Corum', 'Ugurludag', true),

  -- Denizli (19 districts)
  ('Acipayam Belediyesi', 'denizli-acipayam', 'Denizli', 'Acipayam', true),
  ('Babadag Belediyesi', 'denizli-babadag', 'Denizli', 'Babadag', true),
  ('Baklan Belediyesi', 'denizli-baklan', 'Denizli', 'Baklan', true),
  ('Bekilli Belediyesi', 'denizli-bekilli', 'Denizli', 'Bekilli', true),
  ('Beyagac Belediyesi', 'denizli-beyagac', 'Denizli', 'Beyagac', true),
  ('Bozkurt Belediyesi', 'denizli-bozkurt', 'Denizli', 'Bozkurt', true),
  ('Buldan Belediyesi', 'denizli-buldan', 'Denizli', 'Buldan', true),
  ('Cal Belediyesi', 'denizli-cal', 'Denizli', 'Cal', true),
  ('Cameli Belediyesi', 'denizli-cameli', 'Denizli', 'Cameli', true),
  ('Cardak Belediyesi', 'denizli-cardak', 'Denizli', 'Cardak', true),
  ('Civril Belediyesi', 'denizli-civril', 'Denizli', 'Civril', true),
  ('Guney Belediyesi', 'denizli-guney', 'Denizli', 'Guney', true),
  ('Honaz Belediyesi', 'denizli-honaz', 'Denizli', 'Honaz', true),
  ('Kale Belediyesi', 'denizli-kale', 'Denizli', 'Kale', true),
  ('Merkezefendi Belediyesi', 'denizli-merkezefendi', 'Denizli', 'Merkezefendi', true),
  ('Pamukkale Belediyesi', 'denizli-pamukkale', 'Denizli', 'Pamukkale', true),
  ('Saraykoy Belediyesi', 'denizli-saraykoy', 'Denizli', 'Saraykoy', true),
  ('Serinhisar Belediyesi', 'denizli-serinhisar', 'Denizli', 'Serinhisar', true),
  ('Tavas Belediyesi', 'denizli-tavas', 'Denizli', 'Tavas', true),

  -- Diyarbakir (17 districts - existing from 00009, kept unique codes)
  -- Skipping to avoid duplicates

  -- Duzce (8 districts)
  ('Akcakoca Belediyesi', 'duzce-akcakoca', 'Duzce', 'Akcakoca', true),
  ('Cumayeri Belediyesi', 'duzce-cumayeri', 'Duzce', 'Cumayeri', true),
  ('Cilimli Belediyesi', 'duzce-cilimli', 'Duzce', 'Cilimli', true),
  ('Golyaka Belediyesi', 'duzce-golyaka', 'Duzce', 'Golyaka', true),
  ('Gumusova Belediyesi', 'duzce-gumusova', 'Duzce', 'Gumusova', true),
  ('Kaynasli Belediyesi', 'duzce-kaynasli', 'Duzce', 'Kaynasli', true),
  ('Merkez Belediyesi', 'duzce-merkez', 'Duzce', 'Merkez', true),
  ('Yigilca Belediyesi', 'duzce-yigilca', 'Duzce', 'Yigilca', true),

  -- Edirne (9 districts)
  ('Enez Belediyesi', 'edirne-enez', 'Edirne', 'Enez', true),
  ('Havsa Belediyesi', 'edirne-havsa', 'Edirne', 'Havsa', true),
  ('Ipsala Belediyesi', 'edirne-ipsala', 'Edirne', 'Ipsala', true),
  ('Kesan Belediyesi', 'edirne-kesan', 'Edirne', 'Kesan', true),
  ('Lalapasa Belediyesi', 'edirne-lalapasa', 'Edirne', 'Lalapasa', true),
  ('Meric Belediyesi', 'edirne-meric', 'Edirne', 'Meric', true),
  ('Merkez Belediyesi', 'edirne-merkez', 'Edirne', 'Merkez', true),
  ('Suloglu Belediyesi', 'edirne-suloglu', 'Edirne', 'Suloglu', true),
  ('Uzunkopru Belediyesi', 'edirne-uzunkopru', 'Edirne', 'Uzunkopru', true),

  -- Elazig (11 districts)
  ('Agin Belediyesi', 'elazig-agin', 'Elazig', 'Agin', true),
  ('Alacakaya Belediyesi', 'elazig-alacakaya', 'Elazig', 'Alacakaya', true),
  ('Aricak Belediyesi', 'elazig-aricak', 'Elazig', 'Aricak', true),
  ('Baskil Belediyesi', 'elazig-baskil', 'Elazig', 'Baskil', true),
  ('Karakocan Belediyesi', 'elazig-karakocan', 'Elazig', 'Karakocan', true),
  ('Keban Belediyesi', 'elazig-keban', 'Elazig', 'Keban', true),
  ('Kovancilar Belediyesi', 'elazig-kovancilar', 'Elazig', 'Kovancilar', true),
  ('Maden Belediyesi', 'elazig-maden', 'Elazig', 'Maden', true),
  ('Merkez Belediyesi', 'elazig-merkez', 'Elazig', 'Merkez', true),
  ('Palu Belediyesi', 'elazig-palu', 'Elazig', 'Palu', true),
  ('Sivrice Belediyesi', 'elazig-sivrice', 'Elazig', 'Sivrice', true),

  -- Erzincan (9 districts)
  ('Cayirli Belediyesi', 'erzincan-cayirli', 'Erzincan', 'Cayirli', true),
  ('Ilic Belediyesi', 'erzincan-ilic', 'Erzincan', 'Ilic', true),
  ('Kemah Belediyesi', 'erzincan-kemah', 'Erzincan', 'Kemah', true),
  ('Kemaliye Belediyesi', 'erzincan-kemaliye', 'Erzincan', 'Kemaliye', true),
  ('Merkez Belediyesi', 'erzincan-merkez', 'Erzincan', 'Merkez', true),
  ('Otlukbeli Belediyesi', 'erzincan-otlukbeli', 'Erzincan', 'Otlukbeli', true),
  ('Refahiye Belediyesi', 'erzincan-refahiye', 'Erzincan', 'Refahiye', true),
  ('Tercan Belediyesi', 'erzincan-tercan', 'Erzincan', 'Tercan', true),
  ('Uzumlu Belediyesi', 'erzincan-uzumlu', 'Erzincan', 'Uzumlu', true),

  -- Erzurum (20 districts)
  ('Askale Belediyesi', 'erzurum-askale', 'Erzurum', 'Askale', true),
  ('Aziziye Belediyesi', 'erzurum-aziziye', 'Erzurum', 'Aziziye', true),
  ('Cat Belediyesi', 'erzurum-cat', 'Erzurum', 'Cat', true),
  ('Hinis Belediyesi', 'erzurum-hinis', 'Erzurum', 'Hinis', true),
  ('Horasan Belediyesi', 'erzurum-horasan', 'Erzurum', 'Horasan', true),
  ('Ispir Belediyesi', 'erzurum-ispir', 'Erzurum', 'Ispir', true),
  ('Karacoban Belediyesi', 'erzurum-karacoban', 'Erzurum', 'Karacoban', true),
  ('Karayazi Belediyesi', 'erzurum-karayazi', 'Erzurum', 'Karayazi', true),
  ('Koprukoy Belediyesi', 'erzurum-koprukoy', 'Erzurum', 'Koprukoy', true),
  ('Narman Belediyesi', 'erzurum-narman', 'Erzurum', 'Narman', true),
  ('Oltu Belediyesi', 'erzurum-oltu', 'Erzurum', 'Oltu', true),
  ('Olur Belediyesi', 'erzurum-olur', 'Erzurum', 'Olur', true),
  ('Palandoken Belediyesi', 'erzurum-palandoken', 'Erzurum', 'Palandoken', true),
  ('Pasinler Belediyesi', 'erzurum-pasinler', 'Erzurum', 'Pasinler', true),
  ('Pazaryolu Belediyesi', 'erzurum-pazaryolu', 'Erzurum', 'Pazaryolu', true),
  ('Senkaya Belediyesi', 'erzurum-senkaya', 'Erzurum', 'Senkaya', true),
  ('Tekman Belediyesi', 'erzurum-tekman', 'Erzurum', 'Tekman', true),
  ('Tortum Belediyesi', 'erzurum-tortum', 'Erzurum', 'Tortum', true),
  ('Uzundere Belediyesi', 'erzurum-uzundere', 'Erzurum', 'Uzundere', true),
  ('Yakutiye Belediyesi', 'erzurum-yakutiye', 'Erzurum', 'Yakutiye', true),

  -- Eskisehir (14 districts)
  ('Alpu Belediyesi', 'eskisehir-alpu', 'Eskisehir', 'Alpu', true),
  ('Beylikova Belediyesi', 'eskisehir-beylikova', 'Eskisehir', 'Beylikova', true),
  ('Cifteler Belediyesi', 'eskisehir-cifteler', 'Eskisehir', 'Cifteler', true),
  ('Gunyuzu Belediyesi', 'eskisehir-gunyuzu', 'Eskisehir', 'Gunyuzu', true),
  ('Han Belediyesi', 'eskisehir-han', 'Eskisehir', 'Han', true),
  ('Inonu Belediyesi', 'eskisehir-inonu', 'Eskisehir', 'Inonu', true),
  ('Mahmudiye Belediyesi', 'eskisehir-mahmudiye', 'Eskisehir', 'Mahmudiye', true),
  ('Mihalgazi Belediyesi', 'eskisehir-mihalgazi', 'Eskisehir', 'Mihalgazi', true),
  ('Mihaliccik Belediyesi', 'eskisehir-mihaliccik', 'Eskisehir', 'Mihaliccik', true),
  ('Odunpazari Belediyesi', 'eskisehir-odunpazari', 'Eskisehir', 'Odunpazari', true),
  ('Saricakaya Belediyesi', 'eskisehir-saricakaya', 'Eskisehir', 'Saricakaya', true),
  ('Seyitgazi Belediyesi', 'eskisehir-seyitgazi', 'Eskisehir', 'Seyitgazi', true),
  ('Sivrihisar Belediyesi', 'eskisehir-sivrihisar', 'Eskisehir', 'Sivrihisar', true),
  ('Tepebasi Belediyesi', 'eskisehir-tepebasi', 'Eskisehir', 'Tepebasi', true),

  -- Gaziantep (9 districts)
  ('Araban Belediyesi', 'gaziantep-araban', 'Gaziantep', 'Araban', true),
  ('Islahiye Belediyesi', 'gaziantep-islahiye', 'Gaziantep', 'Islahiye', true),
  ('Karkamis Belediyesi', 'gaziantep-karkamis', 'Gaziantep', 'Karkamis', true),
  ('Nizip Belediyesi', 'gaziantep-nizip', 'Gaziantep', 'Nizip', true),
  ('Nurdagi Belediyesi', 'gaziantep-nurdagi', 'Gaziantep', 'Nurdagi', true),
  ('Oguzeli Belediyesi', 'gaziantep-oguzeli', 'Gaziantep', 'Oguzeli', true),
  ('Sahinbey Belediyesi', 'gaziantep-sahinbey', 'Gaziantep', 'Sahinbey', true),
  ('Sehitkamil Belediyesi', 'gaziantep-sehitkamil', 'Gaziantep', 'Sehitkamil', true),
  ('Yavuzeli Belediyesi', 'gaziantep-yavuzeli', 'Gaziantep', 'Yavuzeli', true),

  -- Giresun (16 districts)
  ('Alucra Belediyesi', 'giresun-alucra', 'Giresun', 'Alucra', true),
  ('Bulancak Belediyesi', 'giresun-bulancak', 'Giresun', 'Bulancak', true),
  ('Camoluk Belediyesi', 'giresun-camoluk', 'Giresun', 'Camoluk', true),
  ('Canakci Belediyesi', 'giresun-canakci', 'Giresun', 'Canakci', true),
  ('Dereli Belediyesi', 'giresun-dereli', 'Giresun', 'Dereli', true),
  ('Dogankent Belediyesi', 'giresun-dogankent', 'Giresun', 'Dogankent', true),
  ('Espiye Belediyesi', 'giresun-espiye', 'Giresun', 'Espiye', true),
  ('Eynesil Belediyesi', 'giresun-eynesil', 'Giresun', 'Eynesil', true),
  ('Gorele Belediyesi', 'giresun-gorele', 'Giresun', 'Gorele', true),
  ('Guce Belediyesi', 'giresun-guce', 'Giresun', 'Guce', true),
  ('Kesap Belediyesi', 'giresun-kesap', 'Giresun', 'Kesap', true),
  ('Merkez Belediyesi', 'giresun-merkez', 'Giresun', 'Merkez', true),
  ('Piraziz Belediyesi', 'giresun-piraziz', 'Giresun', 'Piraziz', true),
  ('Sebinkarahisar Belediyesi', 'giresun-sebinkarahisar', 'Giresun', 'Sebinkarahisar', true),
  ('Tirebolu Belediyesi', 'giresun-tirebolu', 'Giresun', 'Tirebolu', true),
  ('Yaglidere Belediyesi', 'giresun-yaglidere', 'Giresun', 'Yaglidere', true),

  -- Gumushane (6 districts)
  ('Kelkit Belediyesi', 'gumushane-kelkit', 'Gumushane', 'Kelkit', true),
  ('Kose Belediyesi', 'gumushane-kose', 'Gumushane', 'Kose', true),
  ('Kurtun Belediyesi', 'gumushane-kurtun', 'Gumushane', 'Kurtun', true),
  ('Merkez Belediyesi', 'gumushane-merkez', 'Gumushane', 'Merkez', true),
  ('Siran Belediyesi', 'gumushane-siran', 'Gumushane', 'Siran', true),
  ('Torul Belediyesi', 'gumushane-torul', 'Gumushane', 'Torul', true),

  -- Hakkari (4 districts)
  ('Cukurca Belediyesi', 'hakkari-cukurca', 'Hakkari', 'Cukurca', true),
  ('Merkez Belediyesi', 'hakkari-merkez', 'Hakkari', 'Merkez', true),
  ('Semdinli Belediyesi', 'hakkari-semdinli', 'Hakkari', 'Semdinli', true),
  ('Yuksekova Belediyesi', 'hakkari-yuksekova', 'Hakkari', 'Yuksekova', true),

  -- Hatay (15 districts)
  ('Altınozu Belediyesi', 'hatay-altinozu', 'Hatay', 'Altinozu', true),
  ('Antakya Belediyesi', 'hatay-antakya', 'Hatay', 'Antakya', true),
  ('Arsuz Belediyesi', 'hatay-arsuz', 'Hatay', 'Arsuz', true),
  ('Belen Belediyesi', 'hatay-belen', 'Hatay', 'Belen', true),
  ('Defne Belediyesi', 'hatay-defne', 'Hatay', 'Defne', true),
  ('Dortyol Belediyesi', 'hatay-dortyol', 'Hatay', 'Dortyol', true),
  ('Erzin Belediyesi', 'hatay-erzin', 'Hatay', 'Erzin', true),
  ('Hassa Belediyesi', 'hatay-hassa', 'Hatay', 'Hassa', true),
  ('Iskenderun Belediyesi', 'hatay-iskenderun', 'Hatay', 'Iskenderun', true),
  ('Kirikhan Belediyesi', 'hatay-kirikhan', 'Hatay', 'Kirikhan', true),
  ('Kumlu Belediyesi', 'hatay-kumlu', 'Hatay', 'Kumlu', true),
  ('Payas Belediyesi', 'hatay-payas', 'Hatay', 'Payas', true),
  ('Reyhanli Belediyesi', 'hatay-reyhanli', 'Hatay', 'Reyhanli', true),
  ('Samandag Belediyesi', 'hatay-samandag', 'Hatay', 'Samandag', true),
  ('Yayladag Belediyesi', 'hatay-yayladag', 'Hatay', 'Yayladag', true),

  -- Igdir (4 districts)
  ('Aralik Belediyesi', 'igdir-aralik', 'Igdir', 'Aralik', true),
  ('Karakoyunlu Belediyesi', 'igdir-karakoyunlu', 'Igdir', 'Karakoyunlu', true),
  ('Merkez Belediyesi', 'igdir-merkez', 'Igdir', 'Merkez', true),
  ('Tuzluca Belediyesi', 'igdir-tuzluca', 'Igdir', 'Tuzluca', true),

  -- Isparta (13 districts)
  ('Aksu Belediyesi', 'isparta-aksu', 'Isparta', 'Aksu', true),
  ('Atabey Belediyesi', 'isparta-atabey', 'Isparta', 'Atabey', true),
  ('Egirdir Belediyesi', 'isparta-egirdir', 'Isparta', 'Egirdir', true),
  ('Gelendost Belediyesi', 'isparta-gelendost', 'Isparta', 'Gelendost', true),
  ('Gonen Belediyesi', 'isparta-gonen', 'Isparta', 'Gonen', true),
  ('Kecborlu Belediyesi', 'isparta-kecborlu', 'Isparta', 'Kecborlu', true),
  ('Merkez Belediyesi', 'isparta-merkez', 'Isparta', 'Merkez', true),
  ('Senirkent Belediyesi', 'isparta-senirkent', 'Isparta', 'Senirkent', true),
  ('Sutculer Belediyesi', 'isparta-sutculer', 'Isparta', 'Sutculer', true),
  ('Sarkikaraagac Belediyesi', 'isparta-sarkikaraagac', 'Isparta', 'Sarkikaraagac', true),
  ('Uluborlu Belediyesi', 'isparta-uluborlu', 'Isparta', 'Uluborlu', true),
  ('Yalvac Belediyesi', 'isparta-yalvac', 'Isparta', 'Yalvac', true),
  ('Yenisarbademli Belediyesi', 'isparta-yenisarbademli', 'Isparta', 'Yenisarbademli', true),

  -- Istanbul (39 districts) - Already exists from 00008
  -- Skipping to avoid duplicates

  -- Izmir (30 districts) - Already exists from 00009
  -- Skipping to avoid duplicates

  -- Kahramanmaras (11 districts)
  ('Afsin Belediyesi', 'kahramanmaras-afsin', 'Kahramanmaras', 'Afsin', true),
  ('Andirin Belediyesi', 'kahramanmaras-andirin', 'Kahramanmaras', 'Andirin', true),
  ('Caglayancerit Belediyesi', 'kahramanmaras-caglayancerit', 'Kahramanmaras', 'Caglayancerit', true),
  ('Dulkadiroglu Belediyesi', 'kahramanmaras-dulkadiroglu', 'Kahramanmaras', 'Dulkadiroglu', true),
  ('Ekinozu Belediyesi', 'kahramanmaras-ekinozu', 'Kahramanmaras', 'Ekinozu', true),
  ('Elbistan Belediyesi', 'kahramanmaras-elbistan', 'Kahramanmaras', 'Elbistan', true),
  ('Goksun Belediyesi', 'kahramanmaras-goksun', 'Kahramanmaras', 'Goksun', true),
  ('Nurhak Belediyesi', 'kahramanmaras-nurhak', 'Kahramanmaras', 'Nurhak', true),
  ('Onikisubat Belediyesi', 'kahramanmaras-onikisubat', 'Kahramanmaras', 'Onikisubat', true),
  ('Pazarcik Belediyesi', 'kahramanmaras-pazarcik', 'Kahramanmaras', 'Pazarcik', true),
  ('Turkoglu Belediyesi', 'kahramanmaras-turkoglu', 'Kahramanmaras', 'Turkoglu', true),

  -- Karabuk (6 districts)
  ('Eflani Belediyesi', 'karabuk-eflani', 'Karabuk', 'Eflani', true),
  ('Eskipazar Belediyesi', 'karabuk-eskipazar', 'Karabuk', 'Eskipazar', true),
  ('Merkez Belediyesi', 'karabuk-merkez', 'Karabuk', 'Merkez', true),
  ('Ovacik Belediyesi', 'karabuk-ovacik', 'Karabuk', 'Ovacik', true),
  ('Safranbolu Belediyesi', 'karabuk-safranbolu', 'Karabuk', 'Safranbolu', true),
  ('Yenice Belediyesi', 'karabuk-yenice', 'Karabuk', 'Yenice', true),

  -- Karaman (6 districts)
  ('Ayranci Belediyesi', 'karaman-ayranci', 'Karaman', 'Ayranci', true),
  ('Basyayla Belediyesi', 'karaman-basyayla', 'Karaman', 'Basyayla', true),
  ('Ermenek Belediyesi', 'karaman-ermenek', 'Karaman', 'Ermenek', true),
  ('Kazimkarabekir Belediyesi', 'karaman-kazimkarabekir', 'Karaman', 'Kazimkarabekir', true),
  ('Merkez Belediyesi', 'karaman-merkez', 'Karaman', 'Merkez', true),
  ('Sariveliler Belediyesi', 'karaman-sariveliler', 'Karaman', 'Sariveliler', true),

  -- Kars (8 districts)
  ('Akyaka Belediyesi', 'kars-akyaka', 'Kars', 'Akyaka', 'true),
  ('Arpacay Belediyesi', 'kars-arpacay', 'Kars', 'Arpacay', true),
  ('Digor Belediyesi', 'kars-digor', 'Kars', 'Digor', true),
  ('Kagizman Belediyesi', 'kars-kagizman', 'Kars', 'Kagizman', true),
  ('Merkez Belediyesi', 'kars-merkez', 'Kars', 'Merkez', true),
  ('Sarikamis Belediyesi', 'kars-sarikamis', 'Kars', 'Sarikamis', true),
  ('Selim Belediyesi', 'kars-selim', 'Kars', 'Selim', true),
  ('Susuz Belediyesi', 'kars-susuz', 'Kars', 'Susuz', true),

  -- Kastamonu (20 districts)
  ('Abana Belediyesi', 'kastamonu-abana', 'Kastamonu', 'Abana', true),
  ('Agli Belediyesi', 'kastamonu-agli', 'Kastamonu', 'Agli', true),
  ('Arac Belediyesi', 'kastamonu-arac', 'Kastamonu', 'Arac', true),
  ('Azdavay Belediyesi', 'kastamonu-azdavay', 'Kastamonu', 'Azdavay', true),
  ('Bozkurt Belediyesi', 'kastamonu-bozkurt', 'Kastamonu', 'Bozkurt', true),
  ('Cide Belediyesi', 'kastamonu-cide', 'Kastamonu', 'Cide', true),
  ('Catalzeytin Belediyesi', 'kastamonu-catalzeytin', 'Kastamonu', 'Catalzeytin', true),
  ('Daday Belediyesi', 'kastamonu-daday', 'Kastamonu', 'Daday', true),
  ('Devrekani Belediyesi', 'kastamonu-devrekani', 'Kastamonu', 'Devrekani', true),
  ('Doganyurt Belediyesi', 'kastamonu-doganyurt', 'Kastamonu', 'Doganyurt', true),
  ('Hanonu Belediyesi', 'kastamonu-hanonu', 'Kastamonu', 'Hanonu', true),
  ('Ihsangazi Belediyesi', 'kastamonu-ihsangazi', 'Kastamonu', 'Ihsangazi', true),
  ('Inebolu Belediyesi', 'kastamonu-inebolu', 'Kastamonu', 'Inebolu', true),
  ('Kure Belediyesi', 'kastamonu-kure', 'Kastamonu', 'Kure', true),
  ('Merkez Belediyesi', 'kastamonu-merkez', 'Kastamonu', 'Merkez', true),
  ('Pinarbasi Belediyesi', 'kastamonu-pinarbasi', 'Kastamonu', 'Pinarbasi', true),
  ('Seydiler Belediyesi', 'kastamonu-seydiler', 'Kastamonu', 'Seydiler', true),
  ('Senpazar Belediyesi', 'kastamonu-senpazar', 'Kastamonu', 'Senpazar', true),
  ('Taskopru Belediyesi', 'kastamonu-taskopru', 'Kastamonu', 'Taskopru', true),
  ('Tosya Belediyesi', 'kastamonu-tosya', 'Kastamonu', 'Tosya', true),

  -- Kayseri (16 districts)
  ('Akkisla Belediyesi', 'kayseri-akkisla', 'Kayseri', 'Akkisla', true),
  ('Bunyan Belediyesi', 'kayseri-bunyan', 'Kayseri', 'Bunyan', true),
  ('Develi Belediyesi', 'kayseri-develi', 'Kayseri', 'Develi', true),
  ('Felahiye Belediyesi', 'kayseri-felahiye', 'Kayseri', 'Felahiye', true),
  ('Hacilar Belediyesi', 'kayseri-hacilar', 'Kayseri', 'Hacilar', true),
  ('Incesu Belediyesi', 'kayseri-incesu', 'Kayseri', 'Incesu', true),
  ('Kocasinan Belediyesi', 'kayseri-kocasinan', 'Kayseri', 'Kocasinan', true),
  ('Melikgazi Belediyesi', 'kayseri-melikgazi', 'Kayseri', 'Melikgazi', true),
  ('Ozvatan Belediyesi', 'kayseri-ozvatan', 'Kayseri', 'Ozvatan', true),
  ('Pinarbasi Belediyesi', 'kayseri-pinarbasi', 'Kayseri', 'Pinarbasi', true),
  ('Sarioglan Belediyesi', 'kayseri-sarioglan', 'Kayseri', 'Sarioglan', true),
  ('Sariz Belediyesi', 'kayseri-sariz', 'Kayseri', 'Sariz', true),
  ('Talas Belediyesi', 'kayseri-talas', 'Kayseri', 'Talas', true),
  ('Tomarza Belediyesi', 'kayseri-tomarza', 'Kayseri', 'Tomarza', true),
  ('Yahyali Belediyesi', 'kayseri-yahyali', 'Kayseri', 'Yahyali', true),
  ('Yesilhisar Belediyesi', 'kayseri-yesilhisar', 'Kayseri', 'Yesilhisar', true),

  -- Kilis (4 districts)
  ('Elbeyli Belediyesi', 'kilis-elbeyli', 'Kilis', 'Elbeyli', true),
  ('Merkez Belediyesi', 'kilis-merkez', 'Kilis', 'Merkez', true),
  ('Musabeyli Belediyesi', 'kilis-musabeyli', 'Kilis', 'Musabeyli', true),
  ('Polateli Belediyesi', 'kilis-polateli', 'Kilis', 'Polateli', true),

  -- Kirikkale (9 districts)
  ('Bahsili Belediyesi', 'kirikkale-bahsili', 'Kirikkale', 'Bahsili', true),
  ('Baliseyh Belediyesi', 'kirikkale-baliseyh', 'Kirikkale', 'Baliseyh', true),
  ('Celebi Belediyesi', 'kirikkale-celebi', 'Kirikkale', 'Celebi', true),
  ('Delice Belediyesi', 'kirikkale-delice', 'Kirikkale', 'Delice', true),
  ('Karakecili Belediyesi', 'kirikkale-karakecili', 'Kirikkale', 'Karakecili', true),
  ('Keskin Belediyesi', 'kirikkale-keskin', 'Kirikkale', 'Keskin', true),
  ('Merkez Belediyesi', 'kirikkale-merkez', 'Kirikkale', 'Merkez', true),
  ('Sulakyurt Belediyesi', 'kirikkale-sulakyurt', 'Kirikkale', 'Sulakyurt', true),
  ('Yahsihan Belediyesi', 'kirikkale-yahsihan', 'Kirikkale', 'Yahsihan', true),

  -- Kirklareli (8 districts)
  ('Babaeski Belediyesi', 'kirklareli-babaeski', 'Kirklareli', 'Babaeski', true),
  ('Demirkoy Belediyesi', 'kirklareli-demirkoy', 'Kirklareli', 'Demirkoy', true),
  ('Kofcaz Belediyesi', 'kirklareli-kofcaz', 'Kirklareli', 'Kofcaz', true),
  ('Luleburgaz Belediyesi', 'kirklareli-luleburgaz', 'Kirklareli', 'Luleburgaz', true),
  ('Merkez Belediyesi', 'kirklareli-merkez', 'Kirklareli', 'Merkez', true),
  ('Pehlivankoy Belediyesi', 'kirklareli-pehlivankoy', 'Kirklareli', 'Pehlivankoy', true),
  ('Pinarhisar Belediyesi', 'kirklareli-pinarhisar', 'Kirklareli', 'Pinarhisar', true),
  ('Vize Belediyesi', 'kirklareli-vize', 'Kirklareli', 'Vize', true),

  -- Kirsehir (7 districts)
  ('Akcakent Belediyesi', 'kirsehir-akcakent', 'Kirsehir', 'Akcakent', true),
  ('Akpinar Belediyesi', 'kirsehir-akpinar', 'Kirsehir', 'Akpinar', true),
  ('Boztepe Belediyesi', 'kirsehir-boztepe', 'Kirsehir', 'Boztepe', true),
  ('Cicekdag Belediyesi', 'kirsehir-cicekdag', 'Kirsehir', 'Cicekdag', true),
  ('Kaman Belediyesi', 'kirsehir-kaman', 'Kirsehir', 'Kaman', true),
  ('Merkez Belediyesi', 'kirsehir-merkez', 'Kirsehir', 'Merkez', true),
  ('Mucur Belediyesi', 'kirsehir-mucur', 'Kirsehir', 'Mucur', true),

  -- Kocaeli (12 districts)
  ('Basiskele Belediyesi', 'kocaeli-basiskele', 'Kocaeli', 'Basiskele', true),
  ('Cayirova Belediyesi', 'kocaeli-cayirova', 'Kocaeli', 'Cayirova', true),
  ('Darica Belediyesi', 'kocaeli-darica', 'Kocaeli', 'Darica', true),
  ('Derince Belediyesi', 'kocaeli-derince', 'Kocaeli', 'Derince', true),
  ('Dilovasi Belediyesi', 'kocaeli-dilovasi', 'Kocaeli', 'Dilovasi', true),
  ('Gebze Belediyesi', 'kocaeli-gebze', 'Kocaeli', 'Gebze', true),
  ('Golcuk Belediyesi', 'kocaeli-golcuk', 'Kocaeli', 'Golcuk', true),
  ('Izmit Belediyesi', 'kocaeli-izmit', 'Kocaeli', 'Izmit', true),
  ('Kandira Belediyesi', 'kocaeli-kandira', 'Kocaeli', 'Kandira', true),
  ('Karamursel Belediyesi', 'kocaeli-karamursel', 'Kocaeli', 'Karamursel', true),
  ('Kartepe Belediyesi', 'kocaeli-kartepe', 'Kocaeli', 'Kartepe', true),
  ('Korfez Belediyesi', 'kocaeli-korfez', 'Kocaeli', 'Korfez', true),

  -- Konya (31 districts)
  ('Ahirli Belediyesi', 'konya-ahirli', 'Konya', 'Ahirli', true),
  ('Akoren Belediyesi', 'konya-akoren', 'Konya', 'Akoren', true),
  ('Aksehir Belediyesi', 'konya-aksehir', 'Konya', 'Aksehir', true),
  ('Altinekin Belediyesi', 'konya-altinekin', 'Konya', 'Altinekin', true),
  ('Beysehir Belediyesi', 'konya-beysehir', 'Konya', 'Beysehir', true),
  ('Bozkir Belediyesi', 'konya-bozkir', 'Konya', 'Bozkir', true),
  ('Cihanbeyli Belediyesi', 'konya-cihanbeyli', 'Konya', 'Cihanbeyli', true),
  ('Celtik Belediyesi', 'konya-celtik', 'Konya', 'Celtik', true),
  ('Cumra Belediyesi', 'konya-cumra', 'Konya', 'Cumra', true),
  ('Derbent Belediyesi', 'konya-derbent', 'Konya', 'Derbent', true),
  ('Derebucak Belediyesi', 'konya-derebucak', 'Konya', 'Derebucak', true),
  ('Doganhisar Belediyesi', 'konya-doganhisar', 'Konya', 'Doganhisar', true),
  ('Emirgazi Belediyesi', 'konya-emirgazi', 'Konya', 'Emirgazi', true),
  ('Eregli Belediyesi', 'konya-eregli', 'Konya', 'Eregli', true),
  ('Guneysinir Belediyesi', 'konya-guneysinir', 'Konya', 'Guneysinir', true),
  ('Hadim Belediyesi', 'konya-hadim', 'Konya', 'Hadim', true),
  ('Halkapinar Belediyesi', 'konya-halkapinar', 'Konya', 'Halkapinar', true),
  ('Huyuk Belediyesi', 'konya-huyuk', 'Konya', 'Huyuk', true),
  ('Ilgin Belediyesi', 'konya-ilgin', 'Konya', 'Ilgin', true),
  ('Kadinhani Belediyesi', 'konya-kadinhani', 'Konya', 'Kadinhani', true),
  ('Karapinar Belediyesi', 'konya-karapinar', 'Konya', 'Karapinar', true),
  ('Karatay Belediyesi', 'konya-karatay', 'Konya', 'Karatay', true),
  ('Kulu Belediyesi', 'konya-kulu', 'Konya', 'Kulu', true),
  ('Meram Belediyesi', 'konya-meram', 'Konya', 'Meram', true),
  ('Sarayonu Belediyesi', 'konya-sarayonu', 'Konya', 'Sarayonu', true),
  ('Selcuklu Belediyesi', 'konya-selcuklu', 'Konya', 'Selcuklu', true),
  ('Seydisehir Belediyesi', 'konya-seydisehir', 'Konya', 'Seydisehir', true),
  ('Taskent Belediyesi', 'konya-taskent', 'Konya', 'Taskent', true),
  ('Tuzlukcu Belediyesi', 'konya-tuzlukcu', 'Konya', 'Tuzlukcu', true),
  ('Yalihuyuk Belediyesi', 'konya-yalihuyuk', 'Konya', 'Yalihuyuk', true),
  ('Yunak Belediyesi', 'konya-yunak', 'Konya', 'Yunak', true),

  -- Kutahya (13 districts)
  ('Altintas Belediyesi', 'kutahya-altintas', 'Kutahya', 'Altintas', true),
  ('Aslanapa Belediyesi', 'kutahya-aslanapa', 'Kutahya', 'Aslanapa', true),
  ('Cavdarhisar Belediyesi', 'kutahya-cavdarhisar', 'Kutahya', 'Cavdarhisar', true),
  ('Domanic Belediyesi', 'kutahya-domanic', 'Kutahya', 'Domanic', true),
  ('Dumlupinar Belediyesi', 'kutahya-dumlupinar', 'Kutahya', 'Dumlupinar', true),
  ('Emet Belediyesi', 'kutahya-emet', 'Kutahya', 'Emet', true),
  ('Gediz Belediyesi', 'kutahya-gediz', 'Kutahya', 'Gediz', true),
  ('Hisarcik Belediyesi', 'kutahya-hisarcik', 'Kutahya', 'Hisarcik', true),
  ('Merkez Belediyesi', 'kutahya-merkez', 'Kutahya', 'Merkez', true),
  ('Pazarlar Belediyesi', 'kutahya-pazarlar', 'Kutahya', 'Pazarlar', true),
  ('Simav Belediyesi', 'kutahya-simav', 'Kutahya', 'Simav', true),
  ('Saphane Belediyesi', 'kutahya-saphane', 'Kutahya', 'Saphane', true),
  ('Tavsanli Belediyesi', 'kutahya-tavsanli', 'Kutahya', 'Tavsanli', true),

  -- Malatya (13 districts)
  ('Akcadag Belediyesi', 'malatya-akcadag', 'Malatya', 'Akcadag', true),
  ('Arapgir Belediyesi', 'malatya-arapgir', 'Malatya', 'Arapgir', true),
  ('Arguvan Belediyesi', 'malatya-arguvan', 'Malatya', 'Arguvan', true),
  ('Battalgazi Belediyesi', 'malatya-battalgazi', 'Malatya', 'Battalgazi', true),
  ('Darende Belediyesi', 'malatya-darende', 'Malatya', 'Darende', true),
  ('Dogansehir Belediyesi', 'malatya-dogansehir', 'Malatya', 'Dogansehir', true),
  ('Doganyol Belediyesi', 'malatya-doganyol', 'Malatya', 'Doganyol', true),
  ('Hekimhan Belediyesi', 'malatya-hekimhan', 'Malatya', 'Hekimhan', true),
  ('Kale Belediyesi', 'malatya-kale', 'Malatya', 'Kale', true),
  ('Kuluncak Belediyesi', 'malatya-kuluncak', 'Malatya', 'Kuluncak', true),
  ('Puturge Belediyesi', 'malatya-puturge', 'Malatya', 'Puturge', true),
  ('Yazihan Belediyesi', 'malatya-yazihan', 'Malatya', 'Yazihan', true),
  ('Yesilurt Belediyesi', 'malatya-yesilurt', 'Malatya', 'Yesilurt', true),

  -- Manisa (17 districts)
  ('Ahmetli Belediyesi', 'manisa-ahmetli', 'Manisa', 'Ahmetli', true),
  ('Akhisar Belediyesi', 'manisa-akhisar', 'Manisa', 'Akhisar', true),
  ('Alasehir Belediyesi', 'manisa-alasehir', 'Manisa', 'Alasehir', true),
  ('Demirci Belediyesi', 'manisa-demirci', 'Manisa', 'Demirci', true),
  ('Golmarmara Belediyesi', 'manisa-golmarmara', 'Manisa', 'Golmarmara', true),
  ('Gordes Belediyesi', 'manisa-gordes', 'Manisa', 'Gordes', true),
  ('Kirkagac Belediyesi', 'manisa-kirkagac', 'Manisa', 'Kirkagac', true),
  ('Koprubasi Belediyesi', 'manisa-koprubasi', 'Manisa', 'Koprubasi', true),
  ('Kula Belediyesi', 'manisa-kula', 'Manisa', 'Kula', true),
  ('Salihli Belediyesi', 'manisa-salihli', 'Manisa', 'Salihli', true),
  ('Sarigol Belediyesi', 'manisa-sarigol', 'Manisa', 'Sarigol', true),
  ('Saruhanli Belediyesi', 'manisa-saruhanli', 'Manisa', 'Saruhanli', true),
  ('Selendi Belediyesi', 'manisa-selendi', 'Manisa', 'Selendi', true),
  ('Soma Belediyesi', 'manisa-soma', 'Manisa', 'Soma', true),
  ('Sehzadeler Belediyesi', 'manisa-sehzadeler', 'Manisa', 'Sehzadeler', true),
  ('Turgutlu Belediyesi', 'manisa-turgutlu', 'Manisa', 'Turgutlu', true),
  ('Yunusemre Belediyesi', 'manisa-yunusemre', 'Manisa', 'Yunusemre', true),

  -- Mardin (10 districts)
  ('Artuklu Belediyesi', 'mardin-artuklu', 'Mardin', 'Artuklu', true),
  ('Dargecit Belediyesi', 'mardin-dargecit', 'Mardin', 'Dargecit', true),
  ('Derik Belediyesi', 'mardin-derik', 'Mardin', 'Derik', true),
  ('Kiziltepe Belediyesi', 'mardin-kiziltepe', 'Mardin', 'Kiziltepe', true),
  ('Mazıdag Belediyesi', 'mardin-mazidag', 'Mardin', 'Mazidag', true),
  ('Midyat Belediyesi', 'mardin-midyat', 'Mardin', 'Midyat', true),
  ('Nusaybin Belediyesi', 'mardin-nusaybin', 'Mardin', 'Nusaybin', true),
  ('Omerli Belediyesi', 'mardin-omerli', 'Mardin', 'Omerli', true),
  ('Savur Belediyesi', 'mardin-savur', 'Mardin', 'Savur', true),
  ('Yesilli Belediyesi', 'mardin-yesilli', 'Mardin', 'Yesilli', true),

  -- Mersin (13 districts)
  ('Akdeniz Belediyesi', 'mersin-akdeniz', 'Mersin', 'Akdeniz', true),
  ('Anamur Belediyesi', 'mersin-anamur', 'Mersin', 'Anamur', true),
  ('Aydincik Belediyesi', 'mersin-aydincik', 'Mersin', 'Aydincik', true),
  ('Bozyazi Belediyesi', 'mersin-bozyazi', 'Mersin', 'Bozyazi', true),
  ('Camliyayla Belediyesi', 'mersin-camliyayla', 'Mersin', 'Camliyayla', true),
  ('Erdemli Belediyesi', 'mersin-erdemli', 'Mersin', 'Erdemli', true),
  ('Gulnar Belediyesi', 'mersin-gulnar', 'Mersin', 'Gulnar', true),
  ('Mezitli Belediyesi', 'mersin-mezitli', 'Mersin', 'Mezitli', true),
  ('Mut Belediyesi', 'mersin-mut', 'Mersin', 'Mut', true),
  ('Silifke Belediyesi', 'mersin-silifke', 'Mersin', 'Silifke', true),
  ('Tarsus Belediyesi', 'mersin-tarsus', 'Mersin', 'Tarsus', true),
  ('Toroslar Belediyesi', 'mersin-toroslar', 'Mersin', 'Toroslar', true),
  ('Yenisehir Belediyesi', 'mersin-yenisehir', 'Mersin', 'Yenisehir', true),

  -- Mugla (13 districts)
  ('Bodrum Belediyesi', 'mugla-bodrum', 'Mugla', 'Bodrum', true),
  ('Dalaman Belediyesi', 'mugla-dalaman', 'Mugla', 'Dalaman', true),
  ('Datca Belediyesi', 'mugla-datca', 'Mugla', 'Datca', true),
  ('Fethiye Belediyesi', 'mugla-fethiye', 'Mugla', 'Fethiye', true),
  ('Kavaklidere Belediyesi', 'mugla-kavaklidere', 'Mugla', 'Kavaklidere', true),
  ('Koycegiz Belediyesi', 'mugla-koycegiz', 'Mugla', 'Koycegiz', true),
  ('Marmaris Belediyesi', 'mugla-marmaris', 'Mugla', 'Marmaris', true),
  ('Mentese Belediyesi', 'mugla-mentese', 'Mugla', 'Mentese', true),
  ('Milas Belediyesi', 'mugla-milas', 'Mugla', 'Milas', true),
  ('Ortaca Belediyesi', 'mugla-ortaca', 'Mugla', 'Ortaca', true),
  ('Seydikemer Belediyesi', 'mugla-seydikemer', 'Mugla', 'Seydikemer', true),
  ('Ula Belediyesi', 'mugla-ula', 'Mugla', 'Ula', true),
  ('Yatagan Belediyesi', 'mugla-yatagan', 'Mugla', 'Yatagan', true),

  -- Mus (6 districts)
  ('Bulanik Belediyesi', 'mus-bulanik', 'Mus', 'Bulanik', true),
  ('Haskoy Belediyesi', 'mus-haskoy', 'Mus', 'Haskoy', true),
  ('Korkut Belediyesi', 'mus-korkut', 'Mus', 'Korkut', true),
  ('Malazgirt Belediyesi', 'mus-malazgirt', 'Mus', 'Malazgirt', true),
  ('Merkez Belediyesi', 'mus-merkez', 'Mus', 'Merkez', true),
  ('Varto Belediyesi', 'mus-varto', 'Mus', 'Varto', true),

  -- Nevsehir (8 districts)
  ('Acigol Belediyesi', 'nevsehir-acigol', 'Nevsehir', 'Acigol', true),
  ('Avanos Belediyesi', 'nevsehir-avanos', 'Nevsehir', 'Avanos', true),
  ('Derinkuyu Belediyesi', 'nevsehir-derinkuyu', 'Nevsehir', 'Derinkuyu', true),
  ('Gulsehir Belediyesi', 'nevsehir-gulsehir', 'Nevsehir', 'Gulsehir', true),
  ('Hacibektas Belediyesi', 'nevsehir-hacibektas', 'Nevsehir', 'Hacibektas', true),
  ('Kozakli Belediyesi', 'nevsehir-kozakli', 'Nevsehir', 'Kozakli', true),
  ('Merkez Belediyesi', 'nevsehir-merkez', 'Nevsehir', 'Merkez', true),
  ('Urgup Belediyesi', 'nevsehir-urgup', 'Nevsehir', 'Urgup', true),

  -- Nigde (6 districts)
  ('Altunhisar Belediyesi', 'nigde-altunhisar', 'Nigde', 'Altunhisar', true),
  ('Bor Belediyesi', 'nigde-bor', 'Nigde', 'Bor', true),
  ('Camardi Belediyesi', 'nigde-camardi', 'Nigde', 'Camardi', true),
  ('Ciftlik Belediyesi', 'nigde-ciftlik', 'Nigde', 'Ciftlik', true),
  ('Merkez Belediyesi', 'nigde-merkez', 'Nigde', 'Merkez', true),
  ('Ulukisla Belediyesi', 'nigde-ulukisla', 'Nigde', 'Ulukisla', true),

  -- Ordu (19 districts)
  ('Akkus Belediyesi', 'ordu-akkus', 'Ordu', 'Akkus', true),
  ('Altinordu Belediyesi', 'ordu-altinordu', 'Ordu', 'Altinordu', true),
  ('Aybasti Belediyesi', 'ordu-aybasti', 'Ordu', 'Aybasti', true),
  ('Camas Belediyesi', 'ordu-camas', 'Ordu', 'Camas', true),
  ('Catalpinar Belediyesi', 'ordu-catalpinar', 'Ordu', 'Catalpinar', true),
  ('Caybasi Belediyesi', 'ordu-caybasi', 'Ordu', 'Caybasi', true),
  ('Fatsa Belediyesi', 'ordu-fatsa', 'Ordu', 'Fatsa', true),
  ('Golkoy Belediyesi', 'ordu-golkoy', 'Ordu', 'Golkoy', true),
  ('Gulyali Belediyesi', 'ordu-gulyali', 'Ordu', 'Gulyali', true),
  ('Gurgentepe Belediyesi', 'ordu-gurgentepe', 'Ordu', 'Gurgentepe', true),
  ('Ikizce Belediyesi', 'ordu-ikizce', 'Ordu', 'Ikizce', true),
  ('Kabaduz Belediyesi', 'ordu-kabaduz', 'Ordu', 'Kabaduz', true),
  ('Kabatas Belediyesi', 'ordu-kabatas', 'Ordu', 'Kabatas', true),
  ('Korgan Belediyesi', 'ordu-korgan', 'Ordu', 'Korgan', true),
  ('Kumru Belediyesi', 'ordu-kumru', 'Ordu', 'Kumru', true),
  ('Mesudiye Belediyesi', 'ordu-mesudiye', 'Ordu', 'Mesudiye', true),
  ('Persembe Belediyesi', 'ordu-persembe', 'Ordu', 'Persembe', true),
  ('Ulubey Belediyesi', 'ordu-ulubey', 'Ordu', 'Ulubey', true),
  ('Unye Belediyesi', 'ordu-unye', 'Ordu', 'Unye', true),

  -- Osmaniye (7 districts)
  ('Bahce Belediyesi', 'osmaniye-bahce', 'Osmaniye', 'Bahce', true),
  ('Duzici Belediyesi', 'osmaniye-duzici', 'Osmaniye', 'Duzici', true),
  ('Hasanbeyli Belediyesi', 'osmaniye-hasanbeyli', 'Osmaniye', 'Hasanbeyli', true),
  ('Kadirli Belediyesi', 'osmaniye-kadirli', 'Osmaniye', 'Kadirli', true),
  ('Merkez Belediyesi', 'osmaniye-merkez', 'Osmaniye', 'Merkez', true),
  ('Sumbas Belediyesi', 'osmaniye-sumbas', 'Osmaniye', 'Sumbas', true),
  ('Toprakkale Belediyesi', 'osmaniye-toprakkale', 'Osmaniye', 'Toprakkale', true),

  -- Rize (12 districts)
  ('Ardesen Belediyesi', 'rize-ardesen', 'Rize', 'Ardesen', true),
  ('Camlihemsin Belediyesi', 'rize-camlihemsin', 'Rize', 'Camlihemsin', true),
  ('Cayeli Belediyesi', 'rize-cayeli', 'Rize', 'Cayeli', true),
  ('Derepazari Belediyesi', 'rize-derepazari', 'Rize', 'Derepazari', true),
  ('Findikli Belediyesi', 'rize-findikli', 'Rize', 'Findikli', true),
  ('Guneysu Belediyesi', 'rize-guneysu', 'Rize', 'Guneysu', true),
  ('Hemsin Belediyesi', 'rize-hemsin', 'Rize', 'Hemsin', true),
  ('Ikizdere Belediyesi', 'rize-ikizdere', 'Rize', 'Ikizdere', true),
  ('Iyidere Belediyesi', 'rize-iyidere', 'Rize', 'Iyidere', true),
  ('Kalkandere Belediyesi', 'rize-kalkandere', 'Rize', 'Kalkandere', true),
  ('Merkez Belediyesi', 'rize-merkez', 'Rize', 'Merkez', true),
  ('Pazar Belediyesi', 'rize-pazar', 'Rize', 'Pazar', true),

  -- Sakarya (16 districts)
  ('Adapazari Belediyesi', 'sakarya-adapazari', 'Sakarya', 'Adapazari', true),
  ('Akyazi Belediyesi', 'sakarya-akyazi', 'Sakarya', 'Akyazi', true),
  ('Arifiye Belediyesi', 'sakarya-arifiye', 'Sakarya', 'Arifiye', true),
  ('Erenler Belediyesi', 'sakarya-erenler', 'Sakarya', 'Erenler', true),
  ('Ferizli Belediyesi', 'sakarya-ferizli', 'Sakarya', 'Ferizli', true),
  ('Geyve Belediyesi', 'sakarya-geyve', 'Sakarya', 'Geyve', true),
  ('Hendek Belediyesi', 'sakarya-hendek', 'Sakarya', 'Hendek', true),
  ('Karapurcek Belediyesi', 'sakarya-karapurcek', 'Sakarya', 'Karapurcek', true),
  ('Karasu Belediyesi', 'sakarya-karasu', 'Sakarya', 'Karasu', true),
  ('Kaynarca Belediyesi', 'sakarya-kaynarca', 'Sakarya', 'Kaynarca', true),
  ('Kocaali Belediyesi', 'sakarya-kocaali', 'Sakarya', 'Kocaali', true),
  ('Pamukova Belediyesi', 'sakarya-pamukova', 'Sakarya', 'Pamukova', true),
  ('Sapanca Belediyesi', 'sakarya-sapanca', 'Sakarya', 'Sapanca', true),
  ('Serdivan Belediyesi', 'sakarya-serdivan', 'Sakarya', 'Serdivan', true),
  ('Sogutlu Belediyesi', 'sakarya-sogutlu', 'Sakarya', 'Sogutlu', true),
  ('Tarakli Belediyesi', 'sakarya-tarakli', 'Sakarya', 'Tarakli', true),

  -- Samsun (17 districts)
  ('Alacam Belediyesi', 'samsun-alacam', 'Samsun', 'Alacam', true),
  ('Asarcik Belediyesi', 'samsun-asarcik', 'Samsun', 'Asarcik', true),
  ('Atakum Belediyesi', 'samsun-atakum', 'Samsun', 'Atakum', true),
  ('Ayvacik Belediyesi', 'samsun-ayvacik', 'Samsun', 'Ayvacik', true),
  ('Bafra Belediyesi', 'samsun-bafra', 'Samsun', 'Bafra', true),
  ('Canik Belediyesi', 'samsun-canik', 'Samsun', 'Canik', true),
  ('Carsamba Belediyesi', 'samsun-carsamba', 'Samsun', 'Carsamba', true),
  ('Havza Belediyesi', 'samsun-havza', 'Samsun', 'Havza', true),
  ('Ilkadim Belediyesi', 'samsun-ilkadim', 'Samsun', 'Ilkadim', true),
  ('Kavak Belediyesi', 'samsun-kavak', 'Samsun', 'Kavak', true),
  ('Ladik Belediyesi', 'samsun-ladik', 'Samsun', 'Ladik', true),
  ('Ondokuzmayis Belediyesi', 'samsun-ondokuzmayis', 'Samsun', 'Ondokuzmayis', true),
  ('Salipazari Belediyesi', 'samsun-salipazari', 'Samsun', 'Salipazari', true),
  ('Tekkekoy Belediyesi', 'samsun-tekkekoy', 'Samsun', 'Tekkekoy', true),
  ('Terme Belediyesi', 'samsun-terme', 'Samsun', 'Terme', true),
  ('Vezirkopru Belediyesi', 'samsun-vezirkopru', 'Samsun', 'Vezirkopru', true),
  ('Yakakent Belediyesi', 'samsun-yakakent', 'Samsun', 'Yakakent', true),

  -- Sanliurfa (13 districts)
  ('Akcakale Belediyesi', 'sanliurfa-akcakale', 'Sanliurfa', 'Akcakale', true),
  ('Birecik Belediyesi', 'sanliurfa-birecik', 'Sanliurfa', 'Birecik', true),
  ('Bozova Belediyesi', 'sanliurfa-bozova', 'Sanliurfa', 'Bozova', true),
  ('Ceylanpinar Belediyesi', 'sanliurfa-ceylanpinar', 'Sanliurfa', 'Ceylanpinar', true),
  ('Eyy ubiye Belediyesi', 'sanliurfa-eyyubiye', 'Sanliurfa', 'Eyyubiye', true),
  ('Halfeti Belediyesi', 'sanliurfa-halfeti', 'Sanliurfa', 'Halfeti', true),
  ('Haliliye Belediyesi', 'sanliurfa-haliliye', 'Sanliurfa', 'Haliliye', true),
  ('Harran Belediyesi', 'sanliurfa-harran', 'Sanliurfa', 'Harran', true),
  ('Hilvan Belediyesi', 'sanliurfa-hilvan', 'Sanliurfa', 'Hilvan', true),
  ('Karakopru Belediyesi', 'sanliurfa-karakopru', 'Sanliurfa', 'Karakopru', true),
  ('Siverek Belediyesi', 'sanliurfa-siverek', 'Sanliurfa', 'Siverek', true),
  ('Suruc Belediyesi', 'sanliurfa-suruc', 'Sanliurfa', 'Suruc', true),
  ('Viransehir Belediyesi', 'sanliurfa-viransehir', 'Sanliurfa', 'Viransehir', true),

  -- Siirt (7 districts)
  ('Baykan Belediyesi', 'siirt-baykan', 'Siirt', 'Baykan', true),
  ('Eruh Belediyesi', 'siirt-eruh', 'Siirt', 'Eruh', true),
  ('Kurtalan Belediyesi', 'siirt-kurtalan', 'Siirt', 'Kurtalan', true),
  ('Merkez Belediyesi', 'siirt-merkez', 'Siirt', 'Merkez', true),
  ('Pervari Belediyesi', 'siirt-pervari', 'Siirt', 'Pervari', true),
  ('Sirvan Belediyesi', 'siirt-sirvan', 'Siirt', 'Sirvan', true),
  ('Tillo Belediyesi', 'siirt-tillo', 'Siirt', 'Tillo', true),

  -- Sinop (9 districts)
  ('Ayancik Belediyesi', 'sinop-ayancik', 'Sinop', 'Ayancik', true),
  ('Boyabat Belediyesi', 'sinop-boyabat', 'Sinop', 'Boyabat', true),
  ('Dikmen Belediyesi', 'sinop-dikmen', 'Sinop', 'Dikmen', true),
  ('Duragan Belediyesi', 'sinop-duragan', 'Sinop', 'Duragan', true),
  ('Erfelek Belediyesi', 'sinop-erfelek', 'Sinop', 'Erfelek', true),
  ('Gerze Belediyesi', 'sinop-gerze', 'Sinop', 'Gerze', true),
  ('Merkez Belediyesi', 'sinop-merkez', 'Sinop', 'Merkez', true),
  ('Sarayduzu Belediyesi', 'sinop-sarayduzu', 'Sinop', 'Sarayduzu', true),
  ('Turkeli Belediyesi', 'sinop-turkeli', 'Sinop', 'Turkeli', true),

  -- Sirnak (7 districts)
  ('Beytussebap Belediyesi', 'sirnak-beytussebap', 'Sirnak', 'Beytussebap', true),
  ('Cizre Belediyesi', 'sirnak-cizre', 'Sirnak', 'Cizre', true),
  ('Guclukonak Belediyesi', 'sirnak-guclukonak', 'Sirnak', 'Guclukonak', true),
  ('Idil Belediyesi', 'sirnak-idil', 'Sirnak', 'Idil', true),
  ('Merkez Belediyesi', 'sirnak-merkez', 'Sirnak', 'Merkez', true),
  ('Silopi Belediyesi', 'sirnak-silopi', 'Sirnak', 'Silopi', true),
  ('Uludere Belediyesi', 'sirnak-uludere', 'Sirnak', 'Uludere', true),

  -- Sivas (17 districts)
  ('Akincilar Belediyesi', 'sivas-akincilar', 'Sivas', 'Akincilar', true),
  ('Altinyayla Belediyesi', 'sivas-altinyayla', 'Sivas', 'Altinyayla', true),
  ('Divrigi Belediyesi', 'sivas-divrigi', 'Sivas', 'Divrigi', true),
  ('Dogansar Belediyesi', 'sivas-dogansar', 'Sivas', 'Dogansar', true),
  ('Gemerek Belediyesi', 'sivas-gemerek', 'Sivas', 'Gemerek', true),
  ('Golova Belediyesi', 'sivas-golova', 'Sivas', 'Golova', true),
  ('Gurun Belediyesi', 'sivas-gurun', 'Sivas', 'Gurun', true),
  ('Hafik Belediyesi', 'sivas-hafik', 'Sivas', 'Hafik', true),
  ('Imranli Belediyesi', 'sivas-imranli', 'Sivas', 'Imranli', true),
  ('Kangal Belediyesi', 'sivas-kangal', 'Sivas', 'Kangal', true),
  ('Koyulhisar Belediyesi', 'sivas-koyulhisar', 'Sivas', 'Koyulhisar', true),
  ('Merkez Belediyesi', 'sivas-merkez', 'Sivas', 'Merkez', true),
  ('Susehri Belediyesi', 'sivas-susehri', 'Sivas', 'Susehri', true),
  ('Sarkisla Belediyesi', 'sivas-sarkisla', 'Sivas', 'Sarkisla', true),
  ('Ulas Belediyesi', 'sivas-ulas', 'Sivas', 'Ulas', true),
  ('Yildizeli Belediyesi', 'sivas-yildizeli', 'Sivas', 'Yildizeli', true),
  ('Zara Belediyesi', 'sivas-zara', 'Sivas', 'Zara', true),

  -- Tekirdag (11 districts)
  ('Cerkezkoy Belediyesi', 'tekirdag-cerkezkoy', 'Tekirdag', 'Cerkezkoy', true),
  ('Corlu Belediyesi', 'tekirdag-corlu', 'Tekirdag', 'Corlu', true),
  ('Ergene Belediyesi', 'tekirdag-ergene', 'Tekirdag', 'Ergene', true),
  ('Hayrabolu Belediyesi', 'tekirdag-hayrabolu', 'Tekirdag', 'Hayrabolu', true),
  ('Kapakli Belediyesi', 'tekirdag-kapakli', 'Tekirdag', 'Kapakli', true),
  ('Malkara Belediyesi', 'tekirdag-malkara', 'Tekirdag', 'Malkara', true),
  ('Marmaraereglis Belediyesi', 'tekirdag-marmaraereglis', 'Tekirdag', 'Marmaraereglis', true),
  ('Muratli Belediyesi', 'tekirdag-muratli', 'Tekirdag', 'Muratli', true),
  ('Saray Belediyesi', 'tekirdag-saray', 'Tekirdag', 'Saray', true),
  ('Suleymanpasa Belediyesi', 'tekirdag-suleymanpasa', 'Tekirdag', 'Suleymanpasa', true),
  ('Sarkoy Belediyesi', 'tekirdag-sarkoy', 'Tekirdag', 'Sarkoy', true),

  -- Tokat (12 districts)
  ('Almus Belediyesi', 'tokat-almus', 'Tokat', 'Almus', true),
  ('Artova Belediyesi', 'tokat-artova', 'Tokat', 'Artova', true),
  ('Basciftlik Belediyesi', 'tokat-basciftlik', 'Tokat', 'Basciftlik', true),
  ('Erbaa Belediyesi', 'tokat-erbaa', 'Tokat', 'Erbaa', true),
  ('Merkez Belediyesi', 'tokat-merkez', 'Tokat', 'Merkez', true),
  ('Niksar Belediyesi', 'tokat-niksar', 'Tokat', 'Niksar', true),
  ('Pazar Belediyesi', 'tokat-pazar', 'Tokat', 'Pazar', true),
  ('Resadiye Belediyesi', 'tokat-resadiye', 'Tokat', 'Resadiye', true),
  ('Sulusaray Belediyesi', 'tokat-sulusaray', 'Tokat', 'Sulusaray', true),
  ('Turhal Belediyesi', 'tokat-turhal', 'Tokat', 'Turhal', true),
  ('Yesilurt Belediyesi', 'tokat-yesilurt', 'Tokat', 'Yesilurt', true),
  ('Zile Belediyesi', 'tokat-zile', 'Tokat', 'Zile', true),

  -- Trabzon (18 districts)
  ('Akcaabat Belediyesi', 'trabzon-akcaabat', 'Trabzon', 'Akcaabat', true),
  ('Arakli Belediyesi', 'trabzon-arakli', 'Trabzon', 'Arakli', true),
  ('Arsin Belediyesi', 'trabzon-arsin', 'Trabzon', 'Arsin', true),
  ('Besikduzu Belediyesi', 'trabzon-besikduzu', 'Trabzon', 'Besikduzu', true),
  ('Carsibasi Belediyesi', 'trabzon-carsibasi', 'Trabzon', 'Carsibasi', true),
  ('Caykara Belediyesi', 'trabzon-caykara', 'Trabzon', 'Caykara', true),
  ('Dernekpazari Belediyesi', 'trabzon-dernekpazari', 'Trabzon', 'Dernekpazari', true),
  ('Duzkoy Belediyesi', 'trabzon-duzkoy', 'Trabzon', 'Duzkoy', true),
  ('Hayrat Belediyesi', 'trabzon-hayrat', 'Trabzon', 'Hayrat', true),
  ('Koprubasi Belediyesi', 'trabzon-koprubasi', 'Trabzon', 'Koprubasi', true),
  ('Macka Belediyesi', 'trabzon-macka', 'Trabzon', 'Macka', true),
  ('Of Belediyesi', 'trabzon-of', 'Trabzon', 'Of', true),
  ('Ortahisar Belediyesi', 'trabzon-ortahisar', 'Trabzon', 'Ortahisar', true),
  ('Salpazari Belediyesi', 'trabzon-salpazari', 'Trabzon', 'Salpazari', true),
  ('Surmene Belediyesi', 'trabzon-surmene', 'Trabzon', 'Surmene', true),
  ('Tonya Belediyesi', 'trabzon-tonya', 'Trabzon', 'Tonya', true),
  ('Vakfikebir Belediyesi', 'trabzon-vakfikebir', 'Trabzon', 'Vakfikebir', true),
  ('Yomra Belediyesi', 'trabzon-yomra', 'Trabzon', 'Yomra', true),

  -- Tunceli (8 districts)
  ('Cemisgezek Belediyesi', 'tunceli-cemisgezek', 'Tunceli', 'Cemisgezek', true),
  ('Hozat Belediyesi', 'tunceli-hozat', 'Tunceli', 'Hozat', true),
  ('Mazgirt Belediyesi', 'tunceli-mazgirt', 'Tunceli', 'Mazgirt', true),
  ('Merkez Belediyesi', 'tunceli-merkez', 'Tunceli', 'Merkez', true),
  ('Nazimiye Belediyesi', 'tunceli-nazimiye', 'Tunceli', 'Nazimiye', true),
  ('Ovacik Belediyesi', 'tunceli-ovacik', 'Tunceli', 'Ovacik', true),
  ('Pertek Belediyesi', 'tunceli-pertek', 'Tunceli', 'Pertek', true),
  ('Pulumur Belediyesi', 'tunceli-pulumur', 'Tunceli', 'Pulumur', true),

  -- Usak (6 districts)
  ('Banaz Belediyesi', 'usak-banaz', 'Usak', 'Banaz', true),
  ('Esme Belediyesi', 'usak-esme', 'Usak', 'Esme', true),
  ('Karahalli Belediyesi', 'usak-karahalli', 'Usak', 'Karahalli', true),
  ('Merkez Belediyesi', 'usak-merkez', 'Usak', 'Merkez', true),
  ('Sivasli Belediyesi', 'usak-sivasli', 'Usak', 'Sivasli', true),
  ('Ulubey Belediyesi', 'usak-ulubey', 'Usak', 'Ulubey', true),

  -- Van (13 districts)
  ('Bahcesaray Belediyesi', 'van-bahcesaray', 'Van', 'Bahcesaray', true),
  ('Baskale Belediyesi', 'van-baskale', 'Van', 'Baskale', true),
  ('Caldiran Belediyesi', 'van-caldiran', 'Van', 'Caldiran', true),
  ('Catak Belediyesi', 'van-catak', 'Van', 'Catak', true),
  ('Edremit Belediyesi', 'van-edremit', 'Van', 'Edremit', true),
  ('Ercis Belediyesi', 'van-ercis', 'Van', 'Ercis', true),
  ('Gevas Belediyesi', 'van-gevas', 'Van', 'Gevas', true),
  ('Gurpinar Belediyesi', 'van-gurpinar', 'Van', 'Gurpinar', true),
  ('Ipekyolu Belediyesi', 'van-ipekyolu', 'Van', 'Ipekyolu', true),
  ('Muradiye Belediyesi', 'van-muradiye', 'Van', 'Muradiye', true),
  ('Ozalp Belediyesi', 'van-ozalp', 'Van', 'Ozalp', true),
  ('Saray Belediyesi', 'van-saray', 'Van', 'Saray', true),
  ('Tusba Belediyesi', 'van-tusba', 'Van', 'Tusba', true),

  -- Yalova (6 districts)
  ('Altinova Belediyesi', 'yalova-altinova', 'Yalova', 'Altinova', true),
  ('Armutlu Belediyesi', 'yalova-armutlu', 'Yalova', 'Armutlu', true),
  ('Cinarcik Belediyesi', 'yalova-cinarcik', 'Yalova', 'Cinarcik', true),
  ('Ciftlikkoy Belediyesi', 'yalova-ciftlikkoy', 'Yalova', 'Ciftlikkoy', true),
  ('Merkez Belediyesi', 'yalova-merkez', 'Yalova', 'Merkez', true),
  ('Termal Belediyesi', 'yalova-termal', 'Yalova', 'Termal', true),

  -- Yozgat (14 districts)
  ('Akdagmadeni Belediyesi', 'yozgat-akdagmadeni', 'Yozgat', 'Akdagmadeni', true),
  ('Aydincik Belediyesi', 'yozgat-aydincik', 'Yozgat', 'Aydincik', true),
  ('Bogazliyan Belediyesi', 'yozgat-bogazliyan', 'Yozgat', 'Bogazliyan', true),
  ('Candir Belediyesi', 'yozgat-candir', 'Yozgat', 'Candir', true),
  ('Cayiralan Belediyesi', 'yozgat-cayiralan', 'Yozgat', 'Cayiralan', true),
  ('Cekerek Belediyesi', 'yozgat-cekerek', 'Yozgat', 'Cekerek', true),
  ('Kadisehri Belediyesi', 'yozgat-kadisehri', 'Yozgat', 'Kadisehri', true),
  ('Merkez Belediyesi', 'yozgat-merkez', 'Yozgat', 'Merkez', true),
  ('Saraykent Belediyesi', 'yozgat-saraykent', 'Yozgat', 'Saraykent', true),
  ('Sarikaya Belediyesi', 'yozgat-sarikaya', 'Yozgat', 'Sarikaya', true),
  ('Sorgun Belediyesi', 'yozgat-sorgun', 'Yozgat', 'Sorgun', true),
  ('Sefaatli Belediyesi', 'yozgat-sefaatli', 'Yozgat', 'Sefaatli', true),
  ('Yenifakili Belediyesi', 'yozgat-yenifakili', 'Yozgat', 'Yenifakili', true),
  ('Yerkoy Belediyesi', 'yozgat-yerkoy', 'Yozgat', 'Yerkoy', true),

  -- Zonguldak (8 districts)
  ('Alapli Belediyesi', 'zonguldak-alapli', 'Zonguldak', 'Alapli', true),
  ('Caycuma Belediyesi', 'zonguldak-caycuma', 'Zonguldak', 'Caycuma', true),
  ('Devrek Belediyesi', 'zonguldak-devrek', 'Zonguldak', 'Devrek', true),
  ('Eregli Belediyesi', 'zonguldak-eregli', 'Zonguldak', 'Eregli', true),
  ('Gokcebey Belediyesi', 'zonguldak-gokcebey', 'Zonguldak', 'Gokcebey', true),
  ('Kilimli Belediyesi', 'zonguldak-kilimli', 'Zonguldak', 'Kilimli', true),
  ('Kozlu Belediyesi', 'zonguldak-kozlu', 'Zonguldak', 'Kozlu', true),
  ('Merkez Belediyesi', 'zonguldak-merkez', 'Zonguldak', 'Merkez', true)

ON CONFLICT (code) DO NOTHING;

COMMIT;

-- Final Statistics
SELECT 
  'Toplam ' || COUNT(*) || ' belediye eklendi' as sonuc
FROM municipalities
WHERE is_active = true;

SELECT 
  city,
  COUNT(*) as belediye_sayisi
FROM municipalities 
WHERE is_active = true
GROUP BY city
ORDER BY city;
